import type { Item, Simulation } from './types';
// The first authored option is correct; deterministic rotation prevents a fixed answer position.
function action(
  id: string,
  phase: string,
  prompt: string,
  context: string,
  choices: string[],
  skillIds: string[],
  explanation: string,
  replies?: string[],
): Item {
  const shift = [...id].reduce((n, c) => n + c.charCodeAt(0), 0) % choices.length;
  const followups: Record<string, string[]> = {
    Query: [
      'Thanks. I will keep that date and status definition with the extract. Next, we need to account for records with missing customer details.',
      'I have recorded that query proposal. Keep the original date and status definition available as you work through the rest of the case.',
    ],
    Join: [
      'Understood. Finance needs the full population represented without repeated monetary amounts. Now help me define the grouped summary.',
      'I have noted your join choice. Missing records and repeated monetary amounts are important risks; use the case file for the next task.',
    ],
    Summarize: [
      'That gives me a decision-focused summary grain. Next, translate the figures into a change I can explain.',
      'I have recorded that summary proposal. We still need a clear interpretation of the agreed metric; use the figures in the case file.',
    ],
    Interpret: [
      'I will carry that interpretation into the briefing. Let’s check what the next piece of evidence can and cannot tell us.',
      'I have noted that interpretation. Keep the original values and uncertainty in view as you make the next recommendation.',
    ],
    Rank: [
      'Thanks. Keep the within-group ranking and its tie rule documented. Now consider which investigation would actually change our decision.',
      'I have recorded that ranking proposal. Next, focus on what additional investigation would help us make the business decision.',
    ],
    Investigate: [
      'That gives us a concrete investigation to discuss. Please turn the findings and their limits into a short stakeholder brief.',
      'I have noted that recommendation. For the final briefing I still need the observed findings, evidence limits, and an actionable next step.',
    ],
    Describe: [
      'Thanks. A useful typical value should still leave room to discuss unusual observations. Next, work with the population in the rate question.',
      'I have recorded that summary. We should keep the unusual observations visible; continue using the population named in the next question.',
    ],
    Calculate: [
      'I will note the population behind that rate. Next, tell me how much certainty we have about the experimental difference.',
      'I have noted that rate calculation. Denominators matter for the decision; next we need to discuss uncertainty in the comparison.',
    ],
    Decide: [
      'I will keep that statistical conclusion separate from the rollout decision. Next, check how the data pipeline represents the population.',
      'I have recorded your decision rule. The planned test and business guardrails both matter; now inspect the data pipeline.',
    ],
    Analyze: [
      'Thanks. The pipeline interpretation will go in our analysis notes. How should we make the comparison readable for the meeting?',
      'I have noted what you think the pipeline returns. Next, choose a display that makes the evidence and its limitations visible.',
    ],
    Visualize: [
      'That display will help the audience see the relevant tradeoff. Let’s move to the recommendation we can act on.',
      'I have recorded your display choice. Our audience still needs the units, comparison and relevant limitations for the next decision.',
    ],
    Clean: [
      'Keep those cleaning rules in the handoff. Next, define the target-attainment calculation using the cleaned records.',
      'I have noted that cleaning proposal. Distinguishing pending work from completed work remains important for the next calculation.',
    ],
    Spreadsheet: [
      'Thanks. The target definition should be explicit in the workbook. Now inspect the scripted summary by group.',
      'I have recorded that workbook proposal. Keep both the status and target conditions in view while you inspect the scripted summary.',
    ],
    Python: [
      'I will note that this summary covers completed work. Now compare it with the queue of work still waiting.',
      'I have recorded your pipeline interpretation. The waiting population also matters; next compare the two weekly metrics.',
    ],
    Brief: [
      'That gives me a finding, a caveat and a next step to take into the meeting. Your recommendation is saved; we will review the evidence after the full assessment.',
      'I need a brief that connects the measured finding, its limits and a useful next step. Your proposed message is saved for the assessment review.',
    ],
  };
  const options = choices.map((text, i) => ({
    text,
    response:
      replies?.[i] ??
      followups[phase]?.[i === 0 ? 0 : 1] ??
      `Your proposed action is recorded. Let's continue with the next part of the case file.`,
  }));
  return {
    id,
    phase,
    prompt,
    context,
    options: [...options.slice(shift), ...options.slice(0, shift)],
    correct: (choices.length - shift) % choices.length,
    explanation,
    skills: skillIds.map((skillId) => ({ skillId, weight: 1 })),
  };
}
export const diagnostic: Simulation[] = [
  {
    id: 'd-revenue',
    title: 'The revenue mystery',
    stakeholder: 'Maya Rao',
    stakeholderRole: 'Growth lead',
    company: 'Harbor Market · fictional retailer',
    brief:
      'Our revenue fell last month. I need to decide whether to increase our marketing budget. Can you find out what happened?',
    data: 'orders(order_id, customer_id, ordered_at, status, amount)\ncustomers(customer_id, region)\norder_items(order_id, sku, quantity)\n\nMonthly summary · INR thousands\n                 January   February\nGross revenue       120        108\nRefunds              10         28\nCompleted orders    200        180\nAd spend             20         20\n\nFebruary support notes: one product had a recall.\nDates are stored as ISO timestamps; amounts are per order.',
    items: [
      action(
        'd-r1',
        'Clarify',
        'What do you ask Maya before querying?',
        'The request says “revenue” but does not define it.',
        [
          'Which revenue definition, time zone, comparison period, and business decision should we use?',
          'Which chart colors do you prefer?',
          'Can I assume revenue means every order ever created?',
          'Shall we double ad spend immediately?',
        ],
        ['clarification', 'reasoning'],
        'Define the metric and decision first. Gross orders and net completed revenue can tell different stories.',
        [
          'Use net revenue of completed orders after refunds, UTC calendar months. Compare January to February and advise whether more ad spend is justified.',
          'Use teal if useful. For the actual decision, use net completed revenue after refunds, UTC months January and February.',
          'Include only completed orders after refunds. Use UTC calendar months January and February; we need an ad-spend decision.',
          'Please analyze first. Net completed revenue after refunds, UTC months January and February, is our decision metric.',
        ],
      ),
      action(
        'd-r2',
        'Query',
        'Which filter safely selects completed February 2026 orders?',
        'ordered_at is a timestamp; all timestamps use UTC.',
        [
          "WHERE status = 'completed' AND ordered_at >= '2026-02-01' AND ordered_at < '2026-03-01'",
          "WHERE ordered_at BETWEEN '2026-02-01' AND '2026-02-28'",
          "WHERE status != 'refunded'",
          'WHERE MONTH(ordered_at) = 2',
        ],
        ['sql-filter'],
        'A half-open month boundary includes all February times and excludes other years, with completed status explicit.',
      ),
      action(
        'd-r3',
        'Join',
        'We need net revenue by region, including orders whose customer record is missing. Which approach is sound?',
        'Orders may contain customer IDs not present in customers; order_items has many rows per order.',
        [
          'LEFT JOIN customers on customer_id; aggregate order amounts once per order, with an Unknown region bucket.',
          'INNER JOIN customers and discard unmatched orders.',
          'Join order_items and sum the order amount on every item row.',
          'CROSS JOIN customers to get every region.',
        ],
        ['sql-joins', 'data-quality'],
        'A left join preserves unmatched orders; joining to order items first could multiply order-level measures.',
      ),
      action(
        'd-r4',
        'Summarize',
        'Find regions with completed-order gross revenue above ₹50,000. Which query shape is right?',
        'Filter completed orders first. Revenue is amount on the orders table.',
        [
          "SELECT region, SUM(amount) FROM orders LEFT JOIN customers USING(customer_id) WHERE status='completed' GROUP BY region HAVING SUM(amount)>50000",
          'SELECT region, amount FROM orders WHERE amount>50000',
          'SELECT region, SUM(amount) FROM orders GROUP BY order_id',
          'SELECT region, SUM(amount) FROM orders WHERE SUM(amount)>50000',
        ],
        ['sql-aggregate'],
        'GROUP BY defines regional grain; HAVING filters aggregated totals. A WHERE filter on amount selects individual orders.',
      ),
      action(
        'd-r5',
        'Interpret',
        'What happened to net revenue after refunds?',
        'January: gross 120, refunds 10. February: gross 108, refunds 28. All values in INR thousands.',
        [
          'It fell from 110 to 80, a decrease of about 27.3%.',
          'It fell by exactly 10%.',
          'It increased from 10 to 28.',
          'It fell by 30 percentage points.',
        ],
        ['interpretation', 'sheet-formulas'],
        'Net revenue = gross − refunds. (80−110)/110 × 100 ≈ −27.3%; a rupee change is not a percentage-point change.',
      ),
      action(
        'd-r6',
        'Rank',
        'How do you return the top two products by net revenue within each region while retaining product rows?',
        'A prior query has one row per region and product with net_revenue already calculated.',
        [
          'Use ROW_NUMBER() OVER (PARTITION BY region ORDER BY net_revenue DESC, product_id), then filter rank <= 2 in an outer query.',
          'Use GROUP BY region alone.',
          'Order all products by revenue and take LIMIT 2.',
          'Use COUNT(*) without partitioning.',
        ],
        ['sql-windows', 'sql-aggregate'],
        'Partitioned row numbers give two products per region. An outer query filters the computed window value; a stable tie-breaker makes the result reproducible.',
      ),
      action(
        'd-r7',
        'Investigate',
        'Is more marketing spend the best immediate recommendation?',
        'Ad spend stayed at 20. Refunds grew from 10 to 28. A recall occurred in February.',
        [
          'Investigate refunds by product and recall dates before recommending more spend; this evidence does not establish marketing effectiveness.',
          'Yes, the revenue decrease proves the ads failed.',
          'No, the recall proves it caused every lost order.',
          'Ignore refunds and extrapolate from gross revenue.',
        ],
        ['reasoning'],
        'The recall is a hypothesis to investigate, not proof of the entire causal effect. Increasing demand before fixing returns may not help.',
      ),
      action(
        'd-r8',
        'Brief',
        'Choose your stakeholder summary.',
        'Maya has one minute and needs a decision and next step.',
        [
          'Net revenue fell 27.3%, with refunds rising sharply. Check recall-linked returns before changing ad spend; we have not established a causal marketing effect.',
          'Our LEFT JOIN and window functions worked.',
          'Marketing caused the decline. Double the budget.',
          'Net revenue fell; no follow-up is needed.',
        ],
        ['communication', 'interpretation'],
        'A useful brief states the measured change, uncertainty, and next action rather than SQL implementation details.',
      ),
    ],
  },
  {
    id: 'd-experiment',
    title: 'Should we ship the new checkout?',
    stakeholder: 'Arjun Shah',
    stakeholderRole: 'Product manager',
    company: 'Parcelly · fictional delivery app',
    brief: 'The new checkout looks promising. Can we roll it out to everyone today?',
    data: 'Randomized user-level experiment · fixed 14-day window\nControl:   1,000 users, 100 purchased\nTreatment: 1,000 users, 120 purchased\nEstimated treatment − control conversion: +2 percentage points\n95% confidence interval: −0.7 to +4.7 percentage points\np-value: 0.15\nPre-agreed significance level: 0.05\n\nOrder values: 200, 220, 240, 260, 2,000 (INR)\nSupport inquiries: mobile 20/200, desktop 5/100\nMissing purchase flags are unknown, not confirmed non-purchases.',
    items: [
      action(
        'd-e1',
        'Clarify',
        'What do you confirm before deciding on rollout?',
        '“Looks promising” is not a pre-agreed success criterion.',
        [
          'Confirm randomization unit, primary metric, guardrails, experiment duration, and the pre-agreed decision rule.',
          'Pick whichever metric improved the most.',
          'Stop the test the first day p < 0.05.',
          'Ask only which team designed the button.',
        ],
        ['clarification', 'testing'],
        'A pre-defined metric and stopping rule reduce cherry-picking. Guardrails prevent optimizing conversion at the expense of customer harm.',
        [
          'Users were randomly assigned for 14 days. Primary metric: purchases per assigned user. Use α=0.05; monitor payment errors and refunds too.',
          'The agreed metric is purchases per assigned user over 14 days, with user-level randomization, α=0.05, and payment-error/refund guardrails.',
          'The full 14-day window and α=0.05 were agreed in advance; primary metric is purchases per assigned user with error/refund guardrails.',
          'The design team is separate. Our agreed experiment uses user randomization, purchases per assigned user, 14 days, α=0.05, and error/refund guardrails.',
        ],
      ),
      action(
        'd-e2',
        'Describe',
        'Which summary best represents a typical value in the five example orders?',
        'Order values are 200, 220, 240, 260, 2,000.',
        [
          'Median ₹240, alongside the distribution and unusually large order.',
          'Mean ₹584 proves most orders are worth ₹584.',
          'Maximum ₹2,000 is the typical order.',
          'Median ₹260 because there are five orders.',
        ],
        ['descriptive'],
        'The sorted middle value is 240. The mean is pulled upward by the large order; showing spread is more informative than hiding it.',
      ),
      action(
        'd-e3',
        'Calculate',
        'What is the support-inquiry probability conditional on mobile use?',
        'Mobile: 20 inquiries / 200 users. Desktop: 5 inquiries / 100 users.',
        ['20/200 = 10%.', '20/300 = 6.7%.', '25/300 = 8.3%.', '200/300 = 66.7%.'],
        ['probability'],
        'Conditional probability uses the population named in the condition: mobile users, not all users.',
      ),
      action(
        'd-e4',
        'Interpret',
        'What does the reported 95% interval support?',
        'Treatment − control: 95% CI from −0.7 to +4.7 percentage points.',
        [
          'The estimate is uncertain and includes zero; both a small decrease and an increase remain compatible with the data.',
          'There is a 95% chance that each user converts.',
          'Treatment is guaranteed to improve conversion by 2 points.',
          'Exactly 95% of users gained 2 points.',
        ],
        ['confidence'],
        'A frequentist interval comes from a procedure with 95% long-run coverage. This interval crosses zero and cannot establish a positive effect at this level.',
      ),
      action(
        'd-e5',
        'Decide',
        'At α = 0.05, what does p = 0.15 mean for the planned decision?',
        'Assume valid randomization and the stated test assumptions.',
        [
          'Do not reject the no-effect null; this is insufficient evidence for improvement, not proof of no effect.',
          'There is a 15% probability that the null is true.',
          'Ship because p is positive.',
          'Prove the two checkouts are identical.',
        ],
        ['testing', 'reasoning'],
        'The p-value is evaluated under the null model. Above α it does not support rejecting the null and does not prove equivalence.',
      ),
      action(
        'd-e6',
        'Analyze',
        'What does this pandas expression produce?',
        'df.drop_duplicates("user_id").groupby("variant")["purchased"].mean()\nAssume one final record per user after deduplication, and flags are valid 0/1.',
        [
          'A purchase rate for each variant based on one retained record per user.',
          'A total revenue sum for each variant.',
          'A duplicate count for each user.',
          'The median order value for all users.',
        ],
        ['python', 'data-quality'],
        'A mean of 0/1 purchase flags is a rate. Deduplication needs a justified rule; unknown flags should be investigated rather than silently treated as zero.',
      ),
      action(
        'd-e7',
        'Visualize',
        'Which visual helps the decision most?',
        'Show conversion and its uncertainty for the two variants.',
        [
          'A labeled rate chart with uncertainty intervals and consistent axes, plus sample sizes.',
          'A 3D pie chart of all 2,000 users.',
          'A bar chart whose axis starts at 9.9% with no interval.',
          'A line chart connecting two unordered variants as a time series.',
        ],
        ['visualization', 'interpretation'],
        'The chart should communicate the comparison and uncertainty. Labels, consistent scales, and sample sizes reduce misleading impressions.',
      ),
      action(
        'd-e8',
        'Brief',
        'How should you answer Arjun?',
        'The treatment rate is 12% vs 10%; its difference interval crosses zero.',
        [
          'The point estimate is +2 points, but evidence is inconclusive at our planned threshold. Check guardrails and plan a properly powered follow-up before broad rollout.',
          'The treatment is 20% better, so success is guaranteed.',
          'No effect exists; cancel every future experiment.',
          'We can test more metrics until one is significant.',
        ],
        ['communication', 'testing'],
        'Communicate the promising estimate and uncertainty together, then suggest a pre-planned next step without cherry-picking.',
      ),
    ],
  },
  {
    id: 'd-service',
    title: 'The support queue briefing',
    stakeholder: 'Leena Das',
    stakeholderRole: 'Operations director',
    company: 'Northstar Helpdesk · fictional support team',
    brief:
      'Our dashboard says resolution times improved, but customers are complaining. Help me prepare tomorrow’s operations briefing.',
    data: 'Ticket extract\nid | channel | created | resolved | hours\nT1 | email   | Mon     | Mon      | 2\nT2 | email   | Mon     | Mon      | 3\nT2 | email   | Mon     | Mon      | 3\nT3 | chat    | Mon     | —        | —\nT4 | phone   | Mon     | Tue      | 18\n\nWeekly resolved-ticket median: 8 hours → 6 hours\nWeekly backlog: 40 → 90 open tickets\nSLA: resolve within 24 hours\nChannels differ in ticket complexity. Export durations may include the text "unknown".\nOnly resolved tickets appear in the current duration chart.',
    items: [
      action(
        'd-s1',
        'Clarify',
        'What would you ask Leena first?',
        'You need to resolve the difference between the dashboard and complaints.',
        [
          'What decision is needed, how is “improvement” defined, and does the chart exclude unresolved tickets or differ by channel?',
          'Can I remove complaining customers?',
          'Should I hide the backlog?',
          'Which font should I use?',
        ],
        ['clarification', 'reasoning'],
        'Metric coverage and business decision matter: a duration chart excluding unresolved work can hide worsening backlog.',
        [
          'We need to allocate staffing. The chart includes only resolved tickets, regardless of channel. Track backlog and the 24-hour SLA as well.',
          'Keep all customers. The staffing decision needs resolved duration, backlog, and the 24-hour SLA, split by channel.',
          'Include the backlog. We need a staffing recommendation using resolved durations, backlog, and 24-hour SLA by channel.',
          'Keep it readable. For staffing, include resolved durations, backlog, and 24-hour SLA by channel; the current chart excludes open work.',
        ],
      ),
      action(
        'd-s2',
        'Clean',
        'Which cleaning plan is defensible?',
        'T2 appears twice; T3 is unresolved with no duration.',
        [
          'Confirm one record per ticket and remove the duplicate T2; preserve T3 as unresolved instead of replacing its duration with zero.',
          'Keep duplicates and replace all missing durations with zero.',
          'Delete every unresolved ticket from all metrics.',
          'Multiply missing durations by the average.',
        ],
        ['data-quality'],
        'A duplicate changes counts and summaries; a missing duration on an open ticket is meaningful, not a zero-hour resolution.',
      ),
      action(
        'd-s3',
        'Spreadsheet',
        'Which spreadsheet approach counts resolved tickets that meet SLA?',
        'Column B = status, column C = numeric hours after cleaning. Open-ticket hours are blank. Count rows with status="resolved" and hours <=24.',
        [
          '=COUNTIFS(B2:B100,"resolved",C2:C100,"<=24")',
          '=SUM(C2:C100)',
          '=COUNTBLANK(C2:C100)',
          '=COUNTIF(C2:C100,">24")',
        ],
        ['sheet-formulas'],
        'COUNTIFS applies both the resolution-status and SLA conditions. The denominator for an SLA rate must be explicitly chosen.',
      ),
      action(
        'd-s4',
        'Python',
        'What does the following expression return?',
        'df.loc[df["status"].eq("resolved")].groupby("channel")["hours"].median()\nAssume cleaned numeric durations and one row per ticket.',
        [
          'Median duration of resolved tickets separately for each channel.',
          'Backlog size for every channel.',
          'Mean duration across all tickets, including open tickets.',
          'The channel with the maximum SLA automatically.',
        ],
        ['python', 'descriptive'],
        'Filter first, then group and take the median. This does not measure waiting time for tickets still open.',
      ),
      action(
        'd-s5',
        'Interpret',
        'Which conclusion follows from the weekly metrics?',
        'Resolved-ticket median: 8 → 6 hours. Backlog: 40 → 90.',
        [
          'Resolved tickets became faster by 25%, but backlog grew 125%; overall service improvement cannot be inferred from duration alone.',
          'Every customer is receiving faster service.',
          'Backlog increased 50%, so nothing changed.',
          'Resolution times fell 2 percentage points.',
        ],
        ['interpretation', 'reasoning'],
        'The two metrics describe different populations. (6−8)/8 = −25%; (90−40)/40 = +125%.',
      ),
      action(
        'd-s6',
        'Visualize',
        'How should the briefing show these two metrics?',
        'Backlog is a count; resolution time is hours.',
        [
          'Two aligned weekly charts with clear units and labels, showing backlog and resolved-ticket median separately.',
          'One unlabeled axis mixing hours and ticket counts.',
          'A pie chart of the 8 and 6 hour medians.',
          'Show only the faster median and omit backlog.',
        ],
        ['visualization'],
        'Separate labeled scales avoid mixing units and make the tension visible. Similar colors alone do not explain two measures.',
      ),
      action(
        'd-s7',
        'Investigate',
        'What is the best next analysis before allocating staff?',
        'Channel complexity differs; overall median decreased.',
        [
          'Compare incoming volume, resolved volume, aging backlog, and SLA by channel and time; check whether the mix of work shifted.',
          'Declare that faster medians prove staffing is sufficient.',
          'Assign every employee to chat without checking volume.',
          'Use the duplicate extract as evidence of double demand.',
        ],
        ['reasoning', 'probability'],
        'Check comparable channel populations and the balance of incoming versus resolved work. Changing mix can create misleading aggregate improvements.',
      ),
      action(
        'd-s8',
        'Brief',
        'Choose the most useful message for Leena.',
        'She needs a staffing recommendation with honest limits.',
        [
          'The resolved median fell 25%, yet backlog grew 125%. Check aging and workload by channel before reallocating staff; the current chart omits unresolved customer waits.',
          'Everything improved. No action required.',
          'Our pandas median is correct, so complaints are wrong.',
          'Hire 20 people immediately; we know the exact cause.',
        ],
        ['communication', 'interpretation'],
        'Explain both signals and the missing coverage, then tie the next analysis to the staffing decision.',
      ),
    ],
  },
];
export const reassessment: Simulation[] = [
  {
    id: 'r-revenue',
    title: 'A subscription renewal puzzle',
    stakeholder: 'Nisha Sen',
    stakeholderRole: 'Finance partner',
    company: 'Fieldnote · fictional SaaS team',
    brief:
      'Renewal income dipped. Should we launch a discount campaign? Please investigate before our budget meeting.',
    data: 'renewals(renewal_id, account_id, paid_at, status, amount)\naccounts(account_id, segment)\nrenewal_lines(renewal_id, product)\n\nMarch gross 200, credits 20; April gross 190, credits 46 (INR thousands).\nOnly paid renewals count. April outages caused some credits.\nAccount segment records may be missing. One renewal may have multiple lines.\nUse UTC calendar months in 2026.',
    items: [
      action(
        'r-r1',
        'Clarify',
        'What is your first question to Nisha?',
        '“Income” and the proposed decision need a shared definition.',
        [
          'Confirm net paid renewal income after credits, comparison months, time zone, and the discount decision.',
          'Ask only for the logo.',
          'Assume every invoice is paid income.',
          'Promise discounts will solve it.',
        ],
        ['clarification', 'reasoning'],
        'Agree on the decision, inclusion rules, metric, and dates.',
        [
          'Yes: paid income minus credits, March vs April 2026, UTC. Recommend whether a discount campaign is justified.',
          'Branding can wait. Use paid income minus credits, March vs April 2026, UTC; evaluate the discount campaign.',
          'Unpaid invoices are excluded. Use net paid income, March/April 2026 UTC for the discount decision.',
          'Please test the evidence. Use net paid income, March/April 2026 UTC for the discount decision.',
        ],
      ),
      action(
        'r-r2',
        'Query',
        'Choose the safe April filter.',
        'paid_at includes time of day.',
        [
          "WHERE status='paid' AND paid_at >= '2026-04-01' AND paid_at < '2026-05-01'",
          "WHERE paid_at <= '2026-04-30'",
          'WHERE MONTH(paid_at)=4',
          "WHERE status='paid' OR paid_at>'2026-04-01'",
        ],
        ['sql-filter'],
        'The half-open UTC range includes the whole month and restricts status and year.',
      ),
      action(
        'r-r3',
        'Join',
        'How do you summarize paid income by account segment without losing unknown accounts?',
        'Renewal amounts are per renewal, while renewal_lines has several rows per renewal.',
        [
          'LEFT JOIN accounts by account_id and keep Unknown segments; avoid summing amounts repeatedly across lines.',
          'INNER JOIN and drop unknown accounts.',
          'CROSS JOIN accounts.',
          'Join renewal_lines and sum each repeated renewal amount.',
        ],
        ['sql-joins', 'data-quality'],
        'Keep unmatched accounts and preserve the renewal grain to avoid duplication.',
      ),
      action(
        'r-r4',
        'Summarize',
        'Which query finds segments whose average paid renewal amount exceeds ₹2,000?',
        'Assume segment has been joined at one row per renewal.',
        [
          "SELECT segment, AVG(amount) FROM joined WHERE status='paid' GROUP BY segment HAVING AVG(amount)>2000",
          'SELECT segment, amount FROM joined WHERE amount>2000',
          'SELECT segment, AVG(amount) FROM joined GROUP BY renewal_id',
          'SELECT segment FROM joined WHERE AVG(amount)>2000',
        ],
        ['sql-aggregate'],
        'Group at segment grain and apply HAVING to the aggregate.',
      ),
      action(
        'r-r5',
        'Interpret',
        'What is the change in net paid income?',
        'March 200−20; April 190−46, in INR thousands.',
        [
          '180 → 144, a 20% decrease.',
          '200 → 190, a 5% net decrease.',
          '20 → 46, a 130% income increase.',
          'A 36 percentage-point decrease.',
        ],
        ['interpretation', 'sheet-formulas'],
        'Subtract credits first, then use the March net value as denominator: (144−180)/180 = −20%.',
      ),
      action(
        'r-r6',
        'Rank',
        'How do you rank renewals by amount separately for each segment, keeping detail?',
        'There is one row per renewal.',
        [
          'ROW_NUMBER() OVER (PARTITION BY segment ORDER BY amount DESC, renewal_id)',
          'GROUP BY segment without detail.',
          'LIMIT 1 over the entire table.',
          'COUNT(segment) without a window.',
        ],
        ['sql-windows', 'sql-aggregate'],
        'A partitioned window ranks within each segment without collapsing rows.',
      ),
      action(
        'r-r7',
        'Investigate',
        'What do you recommend analyzing before a discount campaign?',
        'Net income fell; credits rose during outages.',
        [
          'Separate credit reasons and renewal rates, then investigate outage timing before concluding discounts would help.',
          'Discount immediately because any decrease proves price is the cause.',
          'Conclude outages caused every non-renewal.',
          'Ignore credits because they are inconvenient.',
        ],
        ['reasoning'],
        'Separate possible drivers and avoid an unsupported causal attribution.',
      ),
      action(
        'r-r8',
        'Brief',
        'Choose the finance briefing.',
        'Nisha needs the decision implication, not query syntax.',
        [
          'Net paid renewal income fell 20%; increased credits may be important. Investigate outage-related credits and renewal rates before funding discounts.',
          'SQL windows worked well.',
          'Discounts guarantee recovery.',
          'Gross income fell 5%, so net income also fell 5%.',
        ],
        ['communication', 'interpretation'],
        'Use the agreed metric and connect the evidence and uncertainty to a concrete next action.',
      ),
    ],
  },
  {
    id: 'r-experiment',
    title: 'A notification experiment',
    stakeholder: 'Dev Mehta',
    stakeholderRole: 'Product lead',
    company: 'Trailmap · fictional travel planner',
    brief: 'We tested a reminder notification. Should we send it to all travelers?',
    data: 'Fixed-window user-randomized trial\nControl: 500 users, 50 booked\nTreatment: 500 users, 70 booked\nDifference +4 percentage points; 95% CI +0.2 to +7.8 points; p=0.04\nPre-agreed α=0.05. Notification complaints: control 1%, treatment 8%.\nTrip costs: 100, 120, 130, 150, 1,000\nAmong 80 returning users, 24 booked. Among 120 new users, 12 booked.\nBookings represented as cleaned 0/1 flags, one row per user.',
    items: [
      action(
        'r-e1',
        'Clarify',
        'Which details matter before recommending rollout?',
        'Booking rate improved, but the stakeholder has not mentioned tradeoffs.',
        [
          'Confirm primary metric, user randomization, duration, planned significance rule, and complaint guardrail.',
          'Check only the p-value.',
          'Choose a different metric after seeing results.',
          'Ask only for a color palette.',
        ],
        ['clarification', 'testing'],
        'A decision must respect both the pre-planned statistical test and potential harm.',
        [
          'Booking per assigned user is primary. User-randomized fixed window, α=0.05. Complaint rate above 3% breaches our guardrail.',
          'Also check our complaint guardrail: 3% maximum. Primary booking rate, user randomization, fixed window and α=0.05 were planned.',
          'Keep the planned booking metric. User-randomized fixed window, α=0.05, complaint guardrail 3%.',
          'Visual style later. Use planned booking metric, user randomization, fixed window, α=0.05, and the 3% complaint guardrail.',
        ],
      ),
      action(
        'r-e2',
        'Describe',
        'What describes a typical trip cost without letting the expensive trip dominate?',
        'Costs sorted: 100, 120, 130, 150, 1,000.',
        [
          'Median 130 with the range and outlier noted.',
          'Maximum 1,000.',
          'Mean 300 proves most trips cost 300.',
          'Median 150.',
        ],
        ['descriptive'],
        'The middle value is 130. A robust summary still acknowledges the distribution.',
      ),
      action(
        'r-e3',
        'Calculate',
        'What is the booking probability conditional on being a returning user?',
        '24 of 80 returning users booked; 12 of 120 new users booked.',
        ['24/80 = 30%.', '24/200 = 12%.', '36/200 = 18%.', '80/200 = 40%.'],
        ['probability'],
        'Use the returning-user denominator for a probability conditional on returning.',
      ),
      action(
        'r-e4',
        'Interpret',
        'What does the confidence interval indicate under the stated assumptions?',
        'Treatment difference interval: +0.2 to +7.8 percentage points.',
        [
          'The interval excludes zero and supports a positive booking effect, though its size is uncertain.',
          'Every user is between 0.2% and 7.8% likely to book.',
          'A +4 point gain is certain.',
          'There is no uncertainty because p<0.05.',
        ],
        ['confidence'],
        'An interval excluding zero is consistent with significance for the matching two-sided test, but still has width and assumptions.',
      ),
      action(
        'r-e5',
        'Decide',
        'How do you interpret p=0.04 at α=0.05?',
        'Assume valid test conditions; a complaint guardrail must also pass.',
        [
          'Reject the no-effect null for bookings, then check practical effect and guardrails before rollout.',
          'There is a 4% chance the null is true.',
          'The experiment proves all customers benefit.',
          'Statistical significance automatically overrides the complaint guardrail.',
        ],
        ['testing', 'reasoning'],
        'Statistical evidence for the primary outcome does not remove the need to evaluate harm and practical significance.',
      ),
      action(
        'r-e6',
        'Analyze',
        'Interpret df.groupby("group")["booked"].mean().',
        'booked is a cleaned 0/1 flag with one record per randomized user.',
        [
          'Booking rate by experimental group.',
          'Number of trips by group.',
          'Average trip cost.',
          'The fraction of duplicate users.',
        ],
        ['python', 'data-quality'],
        'Mean of a binary indicator is its proportion, provided the grain and missing-value handling are appropriate.',
      ),
      action(
        'r-e7',
        'Visualize',
        'Which display helps evaluate the notification tradeoff?',
        'Bookings: 10% vs 14%; complaints: 1% vs 8%.',
        [
          'Labeled panels showing booking rates with intervals and complaint rates against the 3% guardrail.',
          'Hide complaint rates and show only bookings.',
          'Use unrelated unlabeled axes.',
          'Pie chart of p-values.',
        ],
        ['visualization', 'interpretation'],
        'Show the benefit, uncertainty, and breached harm threshold together.',
      ),
      action(
        'r-e8',
        'Brief',
        'Which recommendation follows from both outcomes?',
        'The booking test passed, but treatment complaints reached 8% against a 3% limit.',
        [
          'Bookings improved with statistical evidence, but complaints breach the guardrail. Revise the notification and retest rather than roll out unchanged.',
          'Ship because p<0.05 guarantees a good product.',
          'Claim the test found no booking effect.',
          'Delete the complaint metric after the test.',
        ],
        ['communication', 'testing'],
        'A clear recommendation balances the measured benefit with the pre-agreed guardrail.',
      ),
    ],
  },
  {
    id: 'r-service',
    title: 'The warehouse performance review',
    stakeholder: 'Sara Iyer',
    stakeholderRole: 'Fulfillment manager',
    company: 'Cedar Supply · fictional distributor',
    brief:
      'Completed deliveries are faster, yet delayed orders are rising. Can you advise where to focus next week?',
    data: 'shipment_id | zone | status | hours\nS1 | east | delivered | 4\nS2 | west | delivered | 8\nS2 | west | delivered | 8\nS3 | east | pending | —\nS4 | west | delivered | 24\n\nMedian of delivered shipments: 10 → 7 hours\nPending shipments: 60 → 96\nDelivery target: within 20 hours\nZones have different journey lengths. Missing durations for pending shipments are not zero.\nThe dashboard includes only delivered shipments.',
    items: [
      action(
        'r-s1',
        'Clarify',
        'What do you clarify with Sara?',
        '“Faster” describes only completed shipments.',
        [
          'Confirm the staffing decision, delivery target, coverage of pending shipments, and whether results differ by zone.',
          'Ask to delete pending shipments.',
          'Assume customers with pending shipments received fast service.',
          'Ask only about chart colors.',
        ],
        ['clarification', 'reasoning'],
        'Clarify population, target, and decision before inferring improvement.',
        [
          'Allocate next week’s capacity by zone. Use the 20-hour target and aging pending work as well as delivered durations.',
          'Keep pending work. Our capacity decision needs zone-level aging and the 20-hour delivery target.',
          'Pending customers are still waiting. Allocate capacity using zone-level aging, duration, and the 20-hour target.',
          'Readable charts help. The actual decision is capacity by zone, with aging pending work and the 20-hour target.',
        ],
      ),
      action(
        'r-s2',
        'Clean',
        'How do you handle the extract?',
        'S2 is duplicated; S3 is pending with no completed duration.',
        [
          'Confirm unique shipment grain, deduplicate S2, and preserve S3 as pending with unknown completed duration.',
          'Set S3 duration to zero and leave duplicates.',
          'Delete every pending shipment from all reporting.',
          'Count S2 twice to reflect effort.',
        ],
        ['data-quality'],
        'Keep the intended shipment grain and the distinction between pending and zero-duration deliveries.',
      ),
      action(
        'r-s3',
        'Spreadsheet',
        'Which formula counts delivered shipments within the 20-hour target?',
        'Column B holds status; C holds cleaned numeric hours. Pending rows have blank C.',
        [
          '=COUNTIFS(B2:B100,"delivered",C2:C100,"<=20")',
          '=AVERAGE(C2:C100)',
          '=COUNTBLANK(C2:C100)',
          '=COUNTIF(C2:C100,">20")',
        ],
        ['sheet-formulas'],
        'Use both delivered status and duration threshold, then define the denominator if reporting a rate.',
      ),
      action(
        'r-s4',
        'Python',
        'What does df.query("status == \'delivered\'").groupby("zone")["hours"].median() return?',
        'Assume unique shipment rows and cleaned numeric hours.',
        [
          'Delivered-shipment median duration in each zone.',
          'Pending shipment count.',
          'Total workload hours including pending shipments.',
          'The largest zone automatically.',
        ],
        ['python', 'descriptive'],
        'The operation filters delivered shipments, groups by zone, and computes medians of their durations.',
      ),
      action(
        'r-s5',
        'Interpret',
        'What do the weekly changes show?',
        'Delivered median 10 → 7 hours; pending shipments 60 → 96.',
        [
          'Delivered median fell 30%; pending work rose 60%. These metrics alone do not prove overall customer improvement.',
          'Every shipment is 30% faster.',
          'Pending work rose 36%.',
          'Median fell 3 percentage points.',
        ],
        ['interpretation', 'reasoning'],
        'Use the original values as denominators. Completed speed and pending workload cover different parts of the process.',
      ),
      action(
        'r-s6',
        'Visualize',
        'Choose an honest weekly review view.',
        'Hours and pending counts are distinct units.',
        [
          'Aligned charts of delivered median hours and pending counts, with labels and zone filters.',
          'One unlabeled axis mixing hours and counts.',
          'Only a green arrow for completed speed.',
          'A pie chart of median hours.',
        ],
        ['visualization'],
        'Clearly separated units and zone filters help the manager see the service tradeoff.',
      ),
      action(
        'r-s7',
        'Investigate',
        'Which analysis best guides capacity allocation?',
        'Zones differ in route length and incoming shipment volume.',
        [
          'Compare incoming/completed volume, aging pending work, and target attainment within each zone over time.',
          'Assign all staff to the slowest overall median without checking workload.',
          'Treat duplicates as extra demand.',
          'Assume a falling delivered median proves no bottleneck.',
        ],
        ['reasoning', 'probability'],
        'Like-for-like populations and workload flow reveal where capacity is needed, avoiding aggregate mix effects.',
      ),
      action(
        'r-s8',
        'Brief',
        'What do you tell Sara?',
        'She needs a next step tied to the capacity decision.',
        [
          'Delivered median fell 30%, but pending work grew 60%. Compare aging and incoming volume by zone before allocating capacity; pending waits are absent from the current speed chart.',
          'All service improved; keep capacity fixed.',
          'The code runs, so the dashboard is sufficient.',
          'One duplicate proves a zone needs twice the staff.',
        ],
        ['communication', 'interpretation'],
        'State both findings, the reporting limitation, and an actionable investigation.',
      ),
    ],
  },
];
