import type { Topic } from './authoring';
export const javaTopics: Topic[] = [
  {
    key: 'fundamentals',
    name: 'Types, control flow & methods',
    category: 'Java foundations',
    prerequisites: [],
    concept: 'Trace primitive values, references, branches, and method return contracts.',
    intuition: 'A reference can be null; a primitive int cannot. Check loop boundaries explicitly.',
    example:
      'for (int i = 0; i < orders.size(); i++) visits each list index once. int average = 5 / 2 is 2; use an appropriate decimal representation when fractional results matter.',
    checks: [
      [
        'What is int x = 5 / 2?',
        '2',
        '2.5',
        'Compilation always fails',
        'Integer division truncates the fractional part.',
      ],
      [
        'Which value can be null?',
        'An Integer reference',
        'A primitive int',
        'A primitive boolean',
        'Reference types may be null; primitives hold values directly.',
      ],
      [
        'Which loop visits list indices safely?',
        'i = 0; i < list.size(); i++',
        'i = 0; i <= list.size(); i++',
        'i = 1; i <= list.size(); i++',
        'The last valid index is size minus one.',
      ],
      [
        'A method calculates a result for several callers. Best contract?',
        'Accept explicit inputs and return the result',
        'Print only and return nothing',
        'Read all inputs from mutable static fields',
        'Explicit inputs and outputs support reuse and testing.',
      ],
    ],
  },
  {
    key: 'oop',
    name: 'Classes, constructors & encapsulation',
    category: 'Object-oriented design',
    prerequisites: ['fundamentals'],
    concept: 'Construct valid objects and protect invariants behind deliberate methods.',
    intuition:
      'Keep invalid state from entering an object rather than asking every caller to remember the rules.',
    example:
      'Order(int quantity) rejects quantity <= 0. A private quantity field and validated changeQuantity method keep the rule consistent after construction.',
    checks: [
      [
        'What initializes a new object’s required state?',
        'Its constructor',
        'An import statement',
        'A package name',
        'Constructors establish instance state.',
      ],
      [
        'Why keep balance private?',
        'Control changes through invariant-preserving methods',
        'Make tests impossible',
        'Guarantee thread safety automatically',
        'Encapsulation allows controlled validated updates.',
      ],
      [
        'Which design avoids shared order state?',
        'Instance fields per Order',
        'One mutable static order field',
        'Public global fields',
        'Instance state belongs to a particular object.',
      ],
      [
        'How should an invalid constructor quantity be handled?',
        'Reject it clearly before creating usable invalid state',
        'Store it and hope callers correct it',
        'Silently replace it with one',
        'Construction should honor a documented validity contract.',
      ],
    ],
  },
  {
    key: 'interfaces',
    name: 'Interfaces, polymorphism & composition',
    category: 'Object-oriented design',
    prerequisites: ['oop'],
    concept:
      'Program against narrow contracts; preserve substitutability in inheritance and compose independent collaborators.',
    intuition: 'An interface says what is needed; composition chooses who supplies it.',
    example:
      'OrderService accepts an OrderRepository interface. JdbcOrderRepository persists data; FakeOrderRepository records calls in tests. Both satisfy the same narrow contract.',
    checks: [
      [
        'An interface primarily defines?',
        'A behavioral contract',
        'A live database connection',
        'A mandatory shared instance',
        'Interfaces express capabilities implementations must provide.',
      ],
      [
        'PaymentService needs a gateway. Prefer?',
        'Inject a PaymentGateway interface',
        'Extend the gateway to become a service',
        'Call a static production gateway everywhere',
        'Composition separates service decisions from external transport.',
      ],
      [
        'Calling the same interface method on different implementations demonstrates?',
        'Polymorphism',
        'String interning',
        'File parsing',
        'The caller uses one contract with implementation-specific behavior.',
      ],
      [
        'One repository exposes thirty unrelated methods. Improve it.',
        'Introduce a narrow order persistence interface used by the service',
        'Make service depend on every method',
        'Replace all interfaces with static fields',
        'A small contract reduces coupling and makes fakes clear.',
      ],
    ],
  },
  {
    key: 'collections',
    name: 'List, Set & Map selection',
    category: 'Collections & types',
    prerequisites: ['fundamentals'],
    concept: 'Choose collections based on duplicates, order, and key lookup.',
    intuition: 'List is a sequence, Set is membership, Map is keyed association.',
    example:
      'LinkedHashSet<String> records first-seen unique SKU order. Map<String, Integer> holds inventory by SKU; a list preserves display order when duplicates are allowed.',
    checks: [
      [
        'Which collection maps SKU to count?',
        'Map<String, Integer>',
        'List<Integer> without IDs',
        'Set<Integer> counts',
        'A map keeps the key/value association.',
      ],
      [
        'Which prevents duplicate IDs?',
        'Set<String>',
        'ArrayList<String>',
        'StringBuilder',
        'Set semantics enforce uniqueness.',
      ],
      [
        'Which preserves first-insertion order while removing duplicates?',
        'LinkedHashSet',
        'HashSet with an order guarantee',
        'An unordered map key set always',
        'LinkedHashSet explicitly preserves insertion order.',
      ],
      [
        'Need ordered rows and frequent ID lookup. Choose?',
        'A list for rows and a map for lookup, updated consistently',
        'Only a list scanned inside every loop',
        'A set of row counts',
        'Different access patterns can justify coordinated structures.',
      ],
    ],
  },
  {
    key: 'iteration',
    name: 'Iteration & safe collection changes',
    category: 'Collections & types',
    prerequisites: ['collections'],
    concept: 'Traverse collections without invalid indexing or unsafe structural mutation.',
    intuition:
      'Use an iterator’s removal operation or build a filtered result rather than changing an enhanced-for source.',
    example:
      'orders.removeIf(order -> order.isCancelled()) expresses a deletion rule safely. Use a separate filtered list when the original order history must be retained.',
    checks: [
      [
        'Enhanced-for over a List yields?',
        'Each element',
        'Only indices',
        'Only the list size',
        'The loop variable receives each element.',
      ],
      [
        'Removing directly from ArrayList during enhanced-for risks?',
        'ConcurrentModificationException',
        'Guaranteed faster traversal',
        'A compile-time syntax error always',
        'Fail-fast iterators detect structural modification.',
      ],
      [
        'Which safely removes matching elements?',
        'removeIf(predicate)',
        'list.remove inside enhanced-for',
        'Setting list to null',
        'removeIf performs supported conditional removal.',
      ],
      [
        'Audit needs all original rows plus valid rows. Prefer?',
        'Create a filtered result and preserve the source',
        'Delete rejected rows silently',
        'Modify the source while streaming it',
        'Retaining original evidence supports a rejection report and audit.',
      ],
    ],
  },
  {
    key: 'exceptions',
    name: 'Checked & unchecked exceptions',
    category: 'Reliability',
    prerequisites: ['fundamentals'],
    concept: 'Handle recoverable failures and propagate unexpected defects with useful context.',
    intuition:
      'A checked exception requires handling or declaration; neither category should be swallowed as success.',
    example:
      'A repository catches SQLException to wrap it with order context, preserving the cause. The service returns a failure; it must not claim the order was saved.',
    checks: [
      [
        'A checked exception generally must be?',
        'Caught or declared',
        'Ignored automatically',
        'Converted to null always',
        'Java enforces handling or declaration of checked exceptions.',
      ],
      [
        'A NullPointerException is generally?',
        'Unchecked',
        'Always checked',
        'A successful result',
        'It indicates a runtime null dereference.',
      ],
      [
        'Why preserve a wrapped exception’s cause?',
        'Keep original diagnostic evidence',
        'Hide all stack traces forever',
        'Make the operation succeed',
        'The cause connects high-level context to the originating failure.',
      ],
      [
        'A database save fails. What should the service report?',
        'Failure with controlled context and no false success',
        'Success because the exception was caught',
        'An empty successful receipt',
        'Catching an exception does not undo the failed operation.',
      ],
    ],
  },
  {
    key: 'generics',
    name: 'Generics & type safety',
    category: 'Collections & types',
    prerequisites: ['collections'],
    concept: 'Use parameterized types to catch incompatible values before runtime.',
    intuition: 'Declare the type of elements instead of making callers guess and cast.',
    example:
      'List<Order> lets the compiler reject adding a String. A raw List accepts mixed values and pushes mistakes into runtime casts.',
    checks: [
      [
        'What belongs in List<Order>?',
        'Order instances',
        'Any Object without checking',
        'Only String IDs',
        'The type parameter constrains element types.',
      ],
      [
        'Why avoid raw List?',
        'It loses compile-time element type safety',
        'It prevents all allocations',
        'It always keeps insertion order better',
        'Raw types require unchecked assumptions and casts.',
      ],
      [
        'What is a benefit of Map<String, Integer>?',
        'Typed keys and values',
        'Automatic database persistence',
        'Automatic null rejection',
        'Generic parameters describe both sides of the association.',
      ],
      [
        'A helper returns raw List from parsed records. Best improvement?',
        'Validate records and return List<Order> with explicit mapping',
        'Cast the raw list blindly',
        'Disable compiler warnings globally',
        'Validation plus a typed result exposes a reliable contract.',
      ],
    ],
  },
  {
    key: 'strings',
    name: 'String equality & immutability',
    category: 'Java foundations',
    prerequisites: ['fundamentals'],
    concept:
      'Compare String content safely and distinguish immutable values from mutable builders.',
    intuition:
      '== compares references; equals compares content. A new String result does not mutate the original.',
    example:
      '"PAID".equals(status) is null-safe for a possibly null status. status.toLowerCase() returns a new value; assign it if normalization is intended.',
    checks: [
      [
        'How should two String contents be compared?',
        'equals',
        '== always',
        '<=',
        'equals compares content; == tests reference identity.',
      ],
      [
        'Which comparison tolerates a null status?',
        '"PAID".equals(status)',
        'status.equals("PAID")',
        'status.toString() == "PAID"',
        'The non-null literal is the receiver.',
      ],
      [
        'After s.toUpperCase() without assignment, s is?',
        'Unchanged',
        'Always uppercase',
        'null',
        'String operations return new values because String is immutable.',
      ],
      [
        'A loop builds a large report. Prefer?',
        'A local StringBuilder then toString()',
        'Repeated shared static String concatenation',
        'Compare every row using ==',
        'A local builder avoids repeated immutable-string reconstruction and shared state.',
      ],
    ],
  },
  {
    key: 'files',
    name: 'Files & structured data',
    category: 'Backend integration',
    prerequisites: ['exceptions', 'generics'],
    concept: 'Manage file resources and validate parsed records separately from syntax.',
    intuition: 'A parsed JSON document can still violate the application’s contract.',
    example:
      'Use try-with-resources for a BufferedReader. A JSON parser reads structure; a validator checks required ID and non-negative quantity before mapping to an Order.',
    checks: [
      [
        'What closes an AutoCloseable file resource reliably?',
        'try-with-resources',
        'Leaving cleanup to a successful path only',
        'An import statement',
        'Resources close on normal and exceptional exits.',
      ],
      [
        'What handles JSON structure?',
        'A JSON parser',
        'Splitting every comma',
        'String equality alone',
        'A parser understands escaped strings, nesting, and valid syntax.',
      ],
      [
        'A parsed quantity is negative. Next step?',
        'Reject it by domain validation',
        'Accept because parsing passed',
        'Remove the minus character',
        'Syntactic validity does not establish business validity.',
      ],
      [
        'Import fails halfway. What enables safe correction?',
        'Row-specific rejection records and a defined atomic/partial policy',
        'Overwrite source before validation',
        'Silently return success',
        'Explicit policy and evidence make recovery predictable.',
      ],
    ],
  },
  {
    key: 'debugging',
    name: 'Nulls, stack traces & state debugging',
    category: 'Reliability',
    prerequisites: ['exceptions', 'strings'],
    concept: 'Find violated assumptions using a minimal reproduction and relevant stack frames.',
    intuition: 'Identify which value is null before adding broad defensive catches.',
    example:
      'NullPointerException at order.getCustomer().getId() could mean order or customer is null. Reproduce the missing-customer input and validate it at the request boundary.',
    checks: [
      [
        'NullPointerException most directly means?',
        'A null reference was dereferenced',
        'A checked file exception',
        'Every object is invalid',
        'An operation required an object but received null.',
      ],
      [
        'First useful debugging step?',
        'Reproduce with the failing input and inspect the relevant frame',
        'Reinstall all tools',
        'Hide the stack trace',
        'A reproducible failing case narrows investigation.',
      ],
      [
        'A null guard stops the exception but drops an order silently. Is that sufficient?',
        'No; verify the expected missing-data behavior',
        'Yes; no exception means correct behavior',
        'Yes; tests are unnecessary',
        'Correctness includes the contract, not just absence of crashes.',
      ],
      [
        'A bug appears only after repeated calls. Investigate?',
        'Shared mutable state and input sequence with a regression test',
        'Only a single fresh object',
        'String formatting unrelated to the failure',
        'State leakage often depends on call history.',
      ],
    ],
  },
  {
    key: 'testing',
    name: 'JUnit-style unit testing',
    category: 'Reliability',
    prerequisites: ['interfaces', 'debugging'],
    concept: 'Test behavior and failure paths with isolated collaborators and assertions.',
    intuition: 'Arrange a controlled case, invoke the behavior, and assert the contract.',
    example:
      'Arrange a fake repository and a service; submit an invalid order; assertThrows for validation and verify the fake has no save calls. No live database is needed.',
    checks: [
      [
        'What is assertEquals(expected, actual) for?',
        'Checking an expected result',
        'Starting a server',
        'Changing production state',
        'Assertions verify observed behavior.',
      ],
      [
        'Which test avoids a live dependency?',
        'Inject a fake repository',
        'Use production JDBC credentials',
        'Wait for network retries',
        'A fake makes external behavior controllable.',
      ],
      [
        'A rejected order must never persist. What should be asserted?',
        'Validation failure and zero repository save calls',
        'Only that a service exists',
        'Only that a log line printed',
        'Test both the failure and absence of unintended side effects.',
      ],
      [
        'A null-input fix needs which coverage?',
        'Valid input, missing customer, null body, and repository failure',
        'Only a sunny-day example',
        'Only a mocked return without calling the service',
        'Boundary and dependency failures test the real contract.',
      ],
    ],
  },
  {
    key: 'sql',
    name: 'JDBC & parameterized SQL',
    category: 'Backend integration',
    prerequisites: ['exceptions'],
    concept: 'Bind values with PreparedStatement and keep related writes atomic.',
    intuition: 'Treat user input as values, never as SQL syntax.',
    example:
      'PreparedStatement ps = conn.prepareStatement("SELECT id FROM orders WHERE customer_id = ?"); ps.setString(1, customerId). A transfer transaction commits both updates or rolls both back.',
    checks: [
      [
        'How should an external ID enter a JDBC query?',
        'PreparedStatement parameter',
        'String concatenation',
        'eval-style parsing',
        'Binding separates data from SQL syntax.',
      ],
      [
        'JDBC parameter positions normally start at?',
        '1',
        '0',
        '-1',
        'PreparedStatement binding is one-based.',
      ],
      [
        'Two dependent writes should use?',
        'A transaction with rollback on failure',
        'Independent auto-committed writes',
        'A success response after the first write',
        'Atomicity prevents partial business updates.',
      ],
      [
        'A credit fails after a debit. Correct behavior?',
        'Rollback both within the transaction and report failure',
        'Keep the debit and claim success',
        'Catch SQLException and continue committing',
        'Preserve the transfer invariant and expose failure.',
      ],
    ],
  },
  {
    key: 'http',
    name: 'REST, validation & backend layers',
    category: 'Backend integration',
    prerequisites: ['interfaces', 'exceptions'],
    concept: 'Separate HTTP parsing, service policy, and repository persistence.',
    intuition:
      'A handler speaks HTTP; a service owns business decisions; a repository owns storage operations.',
    example:
      'The handler rejects malformed requests with 400; OrderService validates stock; JdbcOrderRepository saves with bound parameters. Inject dependencies so tests can isolate each boundary.',
    checks: [
      [
        'Which HTTP status commonly signals malformed client input?',
        '400',
        '200',
        '500 always',
        '400 indicates a bad request; a success status would mislead clients.',
      ],
      [
        'Where should a stock business rule live?',
        'The service/domain layer',
        'Duplicated in each controller',
        'Only in an HTML form',
        'Central policy remains consistent across entry points.',
      ],
      [
        'What should a repository primarily do?',
        'Access persistence through a narrow contract',
        'Format every HTTP response',
        'Own UI navigation',
        'Repositories separate storage concerns from transport.',
      ],
      [
        'A JSON API and scheduled import create orders. Best design?',
        'Both adapters invoke the same validated service',
        'Duplicate policy in both entry points',
        'Allow imports to bypass stock rules',
        'Shared service behavior prevents inconsistent business outcomes.',
      ],
    ],
  },
  {
    key: 'quality',
    name: 'Readability & safe refactoring',
    category: 'Object-oriented design',
    prerequisites: ['interfaces', 'testing'],
    concept: 'Extract cohesive responsibilities while preserving tested behavior.',
    intuition:
      'A class that needs unrelated reasons to change probably contains multiple responsibilities.',
    example:
      'Extract pricing policy from a controller into a tested service method, then place SQL in a repository. Keep contract tests for the original request/response behavior.',
    checks: [
      [
        'Which method name communicates intent?',
        'calculateInvoiceTotal',
        'processStuff',
        'x',
        'Purposeful naming reduces ambiguity.',
      ],
      [
        'What defines a refactor?',
        'Structural change preserving behavior',
        'Changing acceptance criteria silently',
        'Deleting tests',
        'Behavior remains stable while structure improves.',
      ],
      [
        'A class parses HTTP, calculates prices, and writes SQL. Prefer?',
        'Separate handler, service, and repository',
        'Add more unrelated static methods',
        'Expose every field publicly',
        'Cohesive layers reduce coupling and improve testability.',
      ],
      [
        'What is the safest extraction sequence?',
        'Add behavioral tests, extract one boundary, rerun tests',
        'Rewrite the entire backend without tests',
        'Change business rules and structure together',
        'Small verified changes limit regressions and clarify causes.',
      ],
    ],
  },
  {
    key: 'build',
    name: 'Packages & build dependencies',
    category: 'Java foundations',
    prerequisites: ['fundamentals'],
    concept: 'Organize package names and declare reproducible Maven or Gradle dependencies.',
    intuition: 'The build manifest is the shared recipe; local IDE configuration alone is not.',
    example:
      'Use com.example.orders.service and repository packages. Declare the test library and versions in pom.xml or build.gradle, then run the same build command in CI and locally.',
    checks: [
      [
        'What organizes Java classes into namespaces?',
        'Packages',
        'HTTP status codes',
        'Database rows',
        'Packages group classes and resolve names.',
      ],
      [
        'Where should shared dependency declarations live?',
        'pom.xml or build.gradle',
        'Only in one developer’s IDE',
        'In a screenshot',
        'A build manifest lets others resolve dependencies consistently.',
      ],
      [
        'Why pin compatible dependency versions?',
        'Make builds reproducible',
        'Eliminate all security updates forever',
        'Guarantee every test passes',
        'Declared versions reduce environment-specific surprises.',
      ],
      [
        'A project works only in the author’s IDE. Best repair?',
        'Document the JDK and build command, declare dependencies, verify a clean build',
        'Share IDE screenshots only',
        'Copy all compiled classes without sources',
        'A clean command-line build verifies the reproducible recipe.',
      ],
    ],
  },
  {
    key: 'reasoning',
    name: 'Algorithmic reasoning & lookup costs',
    category: 'Workplace reasoning',
    prerequisites: ['collections'],
    concept: 'Choose algorithms that preserve requirements while limiting repeated work.',
    intuition: 'Explain the invariant and input size before optimizing.',
    example:
      'Build a HashMap of inventory once, then look up each order SKU. This avoids scanning all inventory for every order; keep output order separately if the contract requires it.',
    checks: [
      [
        'One pass over n elements is approximately?',
        'O(n)',
        'O(1) always',
        'O(n cubed)',
        'Linear traversal scales with input count.',
      ],
      [
        'For frequent keyed lookup, generally prefer?',
        'HashMap',
        'Repeated full list scans',
        'One large concatenated String',
        'Hash maps normally provide expected constant-time lookup.',
      ],
      [
        'Before replacing a collection, clarify?',
        'Ordering, duplicate behavior, and input scale',
        'Only the shortest type name',
        'The editor theme',
        'Correctness constraints determine appropriate collection semantics.',
      ],
      [
        'Need first-seen unique events for a large input. Choose?',
        'LinkedHashSet with a defined duplicate key',
        'Sort and discard arrival order',
        'Nested scans for each event',
        'Insertion-ordered uniqueness matches the stated contract efficiently.',
      ],
    ],
  },
  {
    key: 'clarification',
    name: 'Requirement clarification',
    category: 'Workplace skills',
    prerequisites: [],
    concept: 'Confirm null, duplicate, ordering, and failure policies through concrete examples.',
    intuition: 'A testable example makes an ambiguous request actionable.',
    example:
      'Ask whether a second payment request with the same ID should return the original receipt or be rejected. Confirm missing fields must return 400 and never reach the repository.',
    checks: [
      [
        '“Handle duplicates” needs which clarification?',
        'Define the duplicate key and expected response',
        'Choose a color scheme',
        'Remove all repeats without asking',
        'Duplicates are a business policy, not merely a collection choice.',
      ],
      [
        'Which acceptance criterion is measurable?',
        'Null customer returns 400 and creates no order',
        'Make it robust',
        'Use Java well',
        'An observable outcome can be tested.',
      ],
      [
        'A missing customer policy is unclear. Who decides?',
        'The stakeholder accountable for the product contract',
        'An unrelated observer',
        'The exception class alone',
        'Requirements need an accountable business owner.',
      ],
      [
        'A non-blocking policy answer is delayed. Best action?',
        'Document a reversible assumption and progress on independent tasks',
        'Hide the assumption',
        'Stop the whole project',
        'Visible assumptions and isolated policy support safe progress.',
      ],
    ],
  },
  {
    key: 'communication',
    name: 'Explaining fixes & tradeoffs',
    category: 'Workplace skills',
    prerequisites: ['clarification'],
    concept: 'Communicate user impact, tested evidence, remaining risks, and next steps.',
    intuition: 'Stakeholders need the outcome and its limits, not only implementation details.',
    example:
      '“Null customer requests now return 400 without persistence. Valid orders still save in unit tests. A database-outage integration check remains before release.”',
    checks: [
      [
        'Which repair update is useful?',
        'Missing customer now yields 400; valid-order tests pass; outage validation remains',
        'It works now',
        'Java fixed itself',
        'Impact and evidence clarify readiness.',
      ],
      [
        'What does a unit test pass establish?',
        'The tested behavior under controlled dependencies',
        'Guaranteed production availability',
        'Every integration is correct',
        'Evidence is limited to the tested scope.',
      ],
      [
        'Explain a Map tradeoff clearly.',
        'Faster keyed lookup, with ordering managed separately if needed',
        'Maps are always better for everything',
        'No need to discuss ordering',
        'A useful explanation connects benefits to requirements and constraints.',
      ],
      [
        'A release has an untested failure path. What should you say?',
        'Name the remaining risk and propose a targeted validation step',
        'Guarantee success',
        'Only send code lines',
        'Transparent risk and an actionable next step support informed decisions.',
      ],
    ],
  },
];
