import type { Simulation } from '../types';
import { task } from './authoring';
type Decision = [string, string, string, string, string, string, string[]];
function scenario(
  id: string,
  title: string,
  stakeholder: string,
  stakeholderRole: string,
  brief: string,
  data: string,
  decisions: Decision[],
): Simulation {
  const phases = [
    'Clarify',
    'Inspect',
    'Trace',
    'Decide',
    'Implement',
    'Validate',
    'Test',
    'Brief',
  ];
  return {
    id,
    title,
    stakeholder,
    stakeholderRole,
    company: 'Setu Systems · fictional',
    brief,
    data,
    items: decisions.map(([prompt, context, good, bad, worse, explanation, keys], i) =>
      task(
        `${id}-${i + 1}`,
        phases[i],
        prompt,
        context,
        [good, bad, worse],
        explanation,
        'java',
        keys,
        i === 0
          ? [
              `Thanks for checking. ${data} Use that contract for the remaining decisions.`,
              `We still need a precise contract. ${data} Use these requirements for the remaining decisions.`,
            ]
          : undefined,
      ),
    ),
  };
}
export const javaDiagnostic = [
  scenario(
    'java-d-orders',
    'Repair the order service',
    'Meera',
    'Product manager',
    'The order service throws NullPointerException for some requests and still saves invalid quantities. Repair behavior without hiding failures.',
    `Contract: missing order/customer and non-positive quantity return 400, with no save. Valid orders return 201 after saving. Customer IDs are compared by String content. Database failure returns a controlled error, never success.\nCurrent code:\nOrderService.submit(Order order) {\n  if (order.getCustomer().getId() == "VIP") applyDiscount(order);\n  if (order.getQuantity() != 0) repository.save(order);\n}\nTrace: NullPointerException at OrderService.submit, line getCustomer().getId().\nFailing inputs: null order, missing customer, quantity -2.`,
    [
      [
        'What should you ask Meera before repairing the service?',
        'Crashes and invalid orders are both reported.',
        'Confirm missing-customer behavior, quantity boundaries, and persistence acceptance criteria',
        'Ask which IDE she prefers',
        'Promise to catch every exception and return 201',
        'A concrete contract determines both error responses and allowed side effects.',
        ['clarification', 'communication'],
      ],
      [
        'Which quantity check enforces the contract?',
        'Current code accepts every quantity except zero.',
        'Reject quantity <= 0 before saving',
        'Keep quantity != 0',
        'Convert negative quantities to positive silently',
        'Negative quantities pass != 0; explicit positive validation is required.',
        ['fundamentals', 'http'],
      ],
      [
        'What should you investigate from this stack trace?',
        'order.getCustomer().getId() dereferences two references.',
        'Reproduce null order and missing customer; identify the null reference and validate before dereferencing',
        'Reinstall Java',
        'Suppress the trace and assume the save succeeded',
        'The trace identifies a violated input assumption; a minimal reproduction protects the repair.',
        ['debugging', 'exceptions'],
      ],
      [
        'How should VIP customer IDs be compared?',
        'IDs may come from freshly parsed JSON strings.',
        'Use "VIP".equals(customerId) after required-field validation',
        'Use customerId == "VIP"',
        'Assume interned references for every request',
        'equals checks content; == can fail for distinct String objects with identical text.',
        ['strings', 'fundamentals'],
      ],
      [
        'Where should an Order enforce its quantity invariant?',
        'Several adapters can construct an order.',
        'Use validated construction and private state with controlled methods',
        'Expose a public mutable quantity field',
        'Use one mutable static quantity for all orders',
        'Encapsulation keeps each instance valid across callers and later changes.',
        ['oop', 'quality'],
      ],
      [
        'What if the repository throws while saving?',
        'The contract forbids false success.',
        'Propagate a controlled failure preserving the original cause',
        'Catch Exception and return 201',
        'Return a successful empty receipt',
        'An exception does not establish persistence; context and cause support diagnosis.',
        ['exceptions', 'http'],
      ],
      [
        'Which tests should QA run?',
        'Invalid input must never reach persistence.',
        'Valid order, null body, missing customer, zero/negative quantity, equal-content IDs, and repository failure; assert save calls',
        'Only assert that the service was constructed',
        'Only check that no trace is printed',
        'Verify correct outcomes and absence of unintended side effects at boundaries.',
        ['testing', 'debugging'],
      ],
      [
        'What release update is supported?',
        'Unit cases pass; deployment integration remains.',
        'Invalid orders now return 400 without saving; valid orders still save in tests; integration validation remains',
        'All future errors are impossible',
        'We added null checks, so no more testing is needed',
        'Communicate impact, verified evidence, and remaining uncertainty.',
        ['communication', 'reasoning'],
      ],
    ],
  ),
  scenario(
    'java-d-collections',
    'Choose collections for dispatch',
    'Kabir',
    'Dispatch lead',
    'Dispatch sends repeated packages and loses arrival order. Select collections that match the operational rules.',
    `Contract: first-seen unique package ID wins; arrival order must be preserved. Packages have String id and int priority. Need frequent ID lookup for 40,000 packages. Null ID is rejected. A cancellation filter must retain original history for audit. Example IDs ["B","A","B","C"] → ["B","A","C"].\nCurrent code: Set ids = new HashSet(); List packages = new ArrayList();\nfor (Package p : packages) { if (p.cancelled()) packages.remove(p); }`,
    [
      [
        'Which clarification matters before choosing a collection?',
        'The request says remove duplicates.',
        'Confirm the identity key, first-seen order, lookup frequency, and history requirements',
        'Choose whichever collection name is shortest',
        'Sort IDs alphabetically without asking',
        'Collection choice must follow uniqueness and ordering semantics.',
        ['clarification', 'reasoning'],
      ],
      [
        'Which ID container matches the sample output?',
        'B must appear before A despite lexical order.',
        'LinkedHashSet<String>',
        'HashSet with a guaranteed insertion order',
        'ArrayList with no duplicate handling',
        'LinkedHashSet explicitly preserves insertion order while enforcing uniqueness.',
        ['collections', 'generics'],
      ],
      [
        'Why may cancellation removal fail?',
        'The loop removes from the source ArrayList during enhanced-for.',
        'Structural modification invalidates the iterator and may throw ConcurrentModificationException',
        'The list must contain only primitive values',
        'Java cannot loop over objects',
        'Unsafe structural mutation during traversal violates iteration rules.',
        ['iteration', 'debugging'],
      ],
      [
        'How should an ID → package index be represented?',
        'The current repeated scans are slow.',
        'Map<String, Package>, populated consistently with accepted packages',
        'One String containing every package ID',
        'Nested scans of the full list for every lookup',
        'Typed keyed lookup avoids repeated linear searches and makes value contracts explicit.',
        ['collections', 'generics', 'reasoning'],
      ],
      [
        'What should replace raw List storage?',
        'A caller currently casts mixed elements to Package.',
        'List<Package> with validation when mapping external records',
        'Keep a raw List and catch ClassCastException everywhere',
        'Disable type warnings globally',
        'Parameterized collections expose incompatible elements before runtime.',
        ['generics', 'quality'],
      ],
      [
        'How should cancelled output be produced?',
        'Original history must remain available.',
        'Build a new filtered list using safe iteration and retain the original',
        'Delete source elements directly during enhanced-for',
        'Clear history after sending',
        'Separate output from source history; filtering should not destroy audit evidence.',
        ['iteration', 'fundamentals'],
      ],
      [
        'Which checks establish collection correctness?',
        'The sample contains a duplicate and non-sorted arrival order.',
        'Assert B,A,C order, duplicate policy, null ID rejection, cancellation output, and preserved original history',
        'Only assert the collection size is non-negative',
        'Only test already sorted unique input',
        'Tests should distinguish ordering, uniqueness, and mutation policies.',
        ['testing', 'collections'],
      ],
      [
        'How should you explain the chosen design?',
        'A map and ordered unique IDs are implemented.',
        'Ordered IDs preserve arrival sequence; a typed map supports fast lookup; both must stay consistent',
        'Maps guarantee every order automatically',
        'Hashing removes the need for input validation',
        'Explain the benefit and the consistency tradeoff in terms of the dispatch contract.',
        ['communication', 'reasoning'],
      ],
    ],
  ),
  scenario(
    'java-d-backend',
    'Separate a backend controller',
    'Lata',
    'Engineering lead',
    'One Java class parses HTTP, reads files, calculates discounts, and concatenates SQL. Make it testable without changing its contract.',
    `Contract: JSON request fields customer_id and quantity are required; quantity > 0. A CSV adapter uses the same order rules. SQL values must be bound. Repository failures cannot return success. Dependency versions live in pom.xml or build.gradle. Current controller constructs a production database directly, opens a reader without cleanup, and concatenates customer_id into SQL. Public response shape must remain unchanged during refactoring.\nConceptual current class:\nclass OrdersController {\n  Connection connection = ProductionDb.connect();\n  Response submit(String json) {\n    Order order = parser.read(json);\n    connection.createStatement().executeUpdate("INSERT INTO orders VALUES ('" + order.getCustomerId() + "')");\n    return new Response(201, order);\n  }\n}`,
    [
      [
        'What should you establish before extracting classes?',
        'The team wants a maintainable refactor.',
        'Confirm preserved request/response behavior and shared API/CSV validation rules',
        'Change responses to suit the new class layout',
        'Choose inheritance first and test later',
        'Refactoring needs a stable behavioral contract and clear shared policy.',
        ['clarification', 'quality'],
      ],
      [
        'Which responsibility division is appropriate?',
        'Parsing, pricing, and SQL are mixed.',
        'Handler parses HTTP; service owns business rules; repository persists',
        'Every layer validates and calculates differently',
        'Repository formats all HTTP responses',
        'Cohesive layers keep transport, domain, and storage concerns distinct.',
        ['http', 'quality'],
      ],
      [
        'A valid JSON body contains quantity=-1. What is the diagnosis?',
        'Parsing succeeds but invalid orders persist.',
        'Syntax validation was mistaken for domain validation',
        'The JSON parser must be disabled',
        'Every parsed value is trustworthy',
        'Parsed structure still needs type, range, and business checks.',
        ['debugging', 'files', 'fundamentals'],
      ],
      [
        'How should the service depend on persistence?',
        'Unit tests must not need a production database.',
        'Accept a narrow OrderRepository interface via composition',
        'Extend the JDBC connection to become a service',
        'Construct the live database inside each method',
        'Interfaces permit polymorphic real and fake implementations behind an injected boundary.',
        ['interfaces', 'oop'],
      ],
      [
        'How should customer_id enter SQL?',
        'A value may contain apostrophes.',
        'Use PreparedStatement with setString(1, customerId)',
        'Concatenate the value into SQL text',
        'Delete apostrophes and assume safety',
        'Bound parameters separate values from SQL syntax; JDBC indices begin at one.',
        ['sql', 'exceptions'],
      ],
      [
        'How should the import adapter manage resources and setup?',
        'Files and dependency setup need predictable behavior.',
        'Use try-with-resources, validate parsed records, and declare parser/test dependencies in the build manifest',
        'Close readers only after success and rely on IDE libraries',
        'Split every CSV/JSON field by commas',
        'Managed resources survive exceptions; a manifest makes dependencies reproducible.',
        ['files', 'build', 'exceptions'],
      ],
      [
        'Which tests protect the extraction?',
        'Both transports must preserve the same rule.',
        'Contract fixtures plus isolated service tests with fake repository, invalid input, and persistence failure',
        'Only count the number of extracted classes',
        'Only invoke the live database happy path',
        'Behavioral and isolated tests verify unchanged contracts and failure policy.',
        ['testing', 'interfaces'],
      ],
      [
        'How should the refactor be handed off?',
        'Fixtures match; deployment checks remain.',
        'HTTP and CSV share domain rules; persistence is injected; tests preserve responses; integration checks remain',
        'More classes guarantee production reliability',
        'Send only package names and declare victory',
        'Link structural changes to tested outcomes and acknowledge remaining integration work.',
        ['communication', 'build'],
      ],
    ],
  ),
];
export const javaReassessment = [
  scenario(
    'java-r-payments',
    'Make payment retries safe',
    'Aditi',
    'Payments product owner',
    'Repeated requests sometimes debit the same customer twice. Repair retry behavior and protect transaction state.',
    `Contract: payment_id is the idempotency key; a repeat returns the original receipt without another debit. Missing customer or amount <= 0 returns 400. Status text is compared by content. Debit and receipt writes must commit together. JDBC values are bound. A gateway timeout can mean an unknown outcome: reconcile using payment_id rather than retrying a new charge blindly.`,
    [
      [
        'Which policy should you confirm first?',
        'The client retries when it loses a response.',
        'Confirm idempotency key, repeated-response behavior, and uncertain gateway outcomes',
        'Ask the client to never retry',
        'Assume every repeated request creates a new charge',
        'Retry correctness requires an explicit business identity and recovery policy.',
        ['clarification', 'http'],
      ],
      [
        'How should the service identify a repeated payment?',
        'Repeated requests share payment_id.',
        'Use a payment-ID keyed lookup with atomic uniqueness enforcement',
        'Compare only the amount',
        'Search a list of customer names',
        'Stable keyed identity plus atomic enforcement prevents duplicate effects.',
        ['collections', 'reasoning'],
      ],
      [
        'A PAID String from JSON misses a == "PAID" branch. Why?',
        'The text is equal but the objects differ.',
        '== compares references; use content equality with null handling',
        'JSON cannot produce Java Strings',
        'Integer division caused it',
        'Use equals for content; do not rely on object identity for business status.',
        ['strings', 'debugging'],
      ],
      [
        'What should happen for amount=-50 or null customer?',
        'These values violate the contract.',
        'Reject before constructing or persisting a valid payment, preserving private validated state',
        'Take the absolute amount silently',
        'Catch the resulting exception and report success',
        'Validate reference and numeric boundaries and preserve object invariants.',
        ['fundamentals', 'oop', 'exceptions'],
      ],
      [
        'How should debit and receipt be persisted?',
        'A receipt insert can fail after the debit.',
        'One transaction with bound PreparedStatement values and rollback on failure',
        'Commit debit first and ignore receipt errors',
        'Concatenate customer IDs into the query',
        'Atomic bound writes preserve money and the retry record together.',
        ['sql', 'exceptions'],
      ],
      [
        'How should an uncertain timeout be handled?',
        'The gateway might have charged before the connection failed.',
        'Mark uncertainty and reconcile the same payment_id under bounded recovery',
        'Retry a new charge with a new ID immediately',
        'Return a guaranteed paid receipt',
        'Transport failure can leave an unknown business outcome; reconciliation avoids double charging.',
        ['http', 'exceptions'],
      ],
      [
        'Which tests best verify the repair?',
        'Both behavior and state matter.',
        'Repeat payment ID, invalid amount, missing customer, equal-content status, gateway timeout, and transaction rollback',
        'Only assert HTTP 200',
        'Only create a Payment instance',
        'Test duplicate and failure paths along with saved state and absent side effects.',
        ['testing', 'debugging'],
      ],
      [
        'What release brief is supported by unit evidence?',
        'Controlled tests pass; concurrent integration tests remain.',
        'Repeated IDs reuse receipts; invalid inputs reject; rollback tests pass; concurrency/gateway integration remains',
        'No duplicate payment can ever happen again',
        'Tests passed so monitoring is unnecessary',
        'Communicate safeguards, evidence scope, and remaining validation.',
        ['communication', 'reasoning'],
      ],
    ],
  ),
  scenario(
    'java-r-inventory',
    'Repair inventory reconciliation',
    'Dev',
    'Warehouse systems lead',
    'The reconciliation job mixes record types, loses update order, and sometimes crashes while deleting rejected rows.',
    `Input is UTF-8 structured records sku,count,active. Count is int >= 0; zero is valid. First valid occurrence of a SKU wins and arrival order matters. Retain original rows and line-specific rejected records. Example Z/0/true, A/5/true, Z/9/true → Z/0,A/5. Build must run from a declared JDK and Maven/Gradle manifest. Unit tests must isolate file access.`,
    [
      [
        'What do you clarify with Dev?',
        'The job has conflicting duplicate policies.',
        'Confirm zero-count validity, duplicate precedence, output order, and rejection history',
        'Sort everything without asking',
        'Drop all zero-count records',
        'These policies define reconciliation correctness before collection choices.',
        ['clarification', 'communication'],
      ],
      [
        'Which collection design matches the example?',
        'Need ordered unique SKUs and keyed counts.',
        'LinkedHashSet<String> for accepted order plus Map<String,Integer> for counts',
        'HashSet with assumed ordering and a raw mixed List',
        'One concatenated String of records',
        'Use explicit ordering and typed keyed associations, retaining consistent accepted entries.',
        ['collections', 'generics'],
      ],
      [
        'Why does deletion in enhanced-for crash?',
        'The source ArrayList is structurally changed mid-iteration.',
        'Its iterator detects unsupported structural mutation',
        'Integer zero is always null',
        'The package name is missing',
        'Fail-fast iteration can raise ConcurrentModificationException; use supported removal or a separate result.',
        ['iteration', 'debugging'],
      ],
      [
        'What should happen for count 0 versus missing count?',
        'Both currently follow one falsey-like check.',
        'Accept zero and reject missing data with explicit checks',
        'Reject both',
        'Convert missing count to zero silently',
        'A primitive value and an absent parsed reference have different domain meanings.',
        ['fundamentals', 'files'],
      ],
      [
        'Which parser boundary is maintainable?',
        'File loading and calculation are coupled.',
        'Use managed file resources and map validated records into a typed domain list; inject the loader',
        'Keep raw Objects and cast during calculations',
        'Split every structured record at every comma',
        'Resource safety, validation, and typed mapping localize external-data assumptions.',
        ['files', 'generics', 'exceptions'],
      ],
      [
        'How should you refactor and build it?',
        'The job works only in one IDE.',
        'Capture output fixtures, extract pure reconciliation, declare dependencies/JDK, and verify a clean build',
        'Rewrite all rules while deleting tests',
        'Share compiled classes without the manifest',
        'Preserved behavior and a reproducible build reduce maintenance and environment failures.',
        ['quality', 'build'],
      ],
      [
        'Which tests protect correctness at scale?',
        'Original rows must survive filtering.',
        'Zero count, duplicate order, invalid type, preserved source/history, and large repeated-ID fixture with keyed lookup',
        'Only count lines of code',
        'Only test alphabetical unique SKUs',
        'Tests distinguish semantics and exercise repeated work; keyed lookup avoids nested scans.',
        ['testing', 'reasoning', 'iteration'],
      ],
      [
        'How should you brief the warehouse team?',
        'Fixtures pass; production timing has not been measured.',
        'Zero inventory is retained, first-valid order preserved, rejections traceable, and production timing remains to measure',
        'A map guarantees the job is instant',
        'All malformed inputs are now impossible',
        'Report contract outcomes and separate measured correctness from unmeasured performance.',
        ['communication', 'reasoning'],
      ],
    ],
  ),
  scenario(
    'java-r-customers',
    'Refactor a customer API and import',
    'Farah',
    'Backend engineering manager',
    'Customer API and file import apply different validation rules. Unify them and make persistence independently testable.',
    `Contract: required non-null customer_id and plan; plan text is compared by content; unknown plan returns 400. Both REST and JSON-file adapters must call the same service rule. Customer constructor validates required state. Database values are bound; failed writes cannot return success. Preserve existing successful response fields. A Maven/Gradle manifest declares parser and test dependencies.`,
    [
      [
        'What should be agreed before the refactor?',
        'API and import currently disagree on unknown plans.',
        'Confirm shared plan validation, required fields, and preserved response examples',
        'Choose separate policies per adapter for convenience',
        'Begin by renaming every package',
        'A shared observable contract aligns both entry points and protects current clients.',
        ['clarification', 'quality'],
      ],
      [
        'Which backend split is appropriate?',
        'One controller parses files, validates plans, and writes SQL.',
        'Transport adapters parse; CustomerService applies rules; repository persists',
        'Make the repository own HTTP and file responses',
        'Duplicate each rule in each adapter',
        'Separate responsibilities with one shared domain operation.',
        ['http', 'quality'],
      ],
      [
        'How should plan comparisons and missing fields be handled?',
        'A parsed plan may be null or a fresh String object.',
        'Validate required values, then compare plan contents with equals',
        'Use == and assume interning',
        'Call toString on null and catch the exception as success',
        'Missing-state validation and content equality address separate failure causes.',
        ['strings', 'debugging', 'exceptions'],
      ],
      [
        'How can the service support test and production repositories?',
        'No production database should be needed by a unit test.',
        'Inject a CustomerRepository interface with real/fake implementations; construct validated Customer instances',
        'Subclass a database connection as CustomerService',
        'Use public mutable static customer state',
        'Interfaces support polymorphism; composition and encapsulation protect the domain boundary.',
        ['interfaces', 'oop'],
      ],
      [
        'How should a customer update be executed?',
        'customer_id may contain quotes.',
        'PreparedStatement with setString parameters and controlled failure handling',
        'Concatenate quotes into SQL text',
        'Catch SQL errors and return a success response',
        'Binding preserves values without executing input as SQL; failures must remain failures.',
        ['sql', 'exceptions'],
      ],
      [
        'How should the JSON import and project setup behave?',
        'Files can be malformed and resources must close.',
        'Use a structured parser with schema/domain validation, try-with-resources, and declared parser/test versions',
        'Split JSON on commas and rely on local IDE plugins',
        'Accept any parsed object and leave readers open',
        'Parsing, validation, cleanup, and reproducible dependencies are distinct requirements.',
        ['files', 'build'],
      ],
      [
        'Which verification establishes consistency?',
        'Both adapters must preserve successful response fields.',
        'Run matching valid/invalid fixtures through both adapters and isolated service tests with repository failures',
        'Only compare class names',
        'Only test one adapter’s valid request',
        'Contract fixtures catch divergence while controlled failures test persistence policy.',
        ['testing', 'interfaces', 'fundamentals'],
      ],
      [
        'What should the handoff state?',
        'Contract fixtures and isolated tests pass; live deployment checks remain.',
        'Both entry points share validated service rules and typed persistence; fixtures pass; integration verification remains',
        'More interfaces prove every business rule forever',
        'Only list packages and promise flawless deployment',
        'Explain behavior and evidence in stakeholder terms with clear remaining checks.',
        ['communication', 'reasoning'],
      ],
    ],
  ),
];
