import type { Topic } from './authoring';
export const pythonTopics: Topic[] = [
  {
    key: 'fundamentals',
    name: 'Values, branches & loops',
    category: 'Python foundations',
    prerequisites: [],
    concept: 'Trace values, truth conditions, and loop boundaries before changing behavior.',
    intuition:
      'Follow one concrete input through every branch; zero is a value, not a missing value.',
    example:
      'A shipping loop uses if quantity > 0 before adding price * quantity. For quantities [0, 2], only the second row contributes. Test zero and negative quantities separately.',
    checks: [
      [
        'What does sum([2, 3]) return?',
        '5',
        '23',
        '[2, 3]',
        'sum adds numeric values, unlike string concatenation.',
      ],
      [
        'A stock value can be zero or None. Which detects missing stock only?',
        'stock is None',
        'not stock',
        'stock == 0',
        'None identifies absence; truthiness also matches zero.',
      ],
      [
        'Which loop visits three rows by index?',
        'range(3)',
        'range(1, 3)',
        'range(4)',
        'range stops before its upper bound: 0, 1, 2.',
      ],
      [
        'An order has quantity -2. What should a processor do before charging?',
        'Reject the invalid quantity with a clear validation result',
        'Use abs(quantity) silently',
        'Process it because it is truthy',
        'Validation preserves the contract; coercing negative quantities creates unintended orders.',
      ],
    ],
  },
  {
    key: 'functions',
    name: 'Functions & scope',
    category: 'Python foundations',
    prerequisites: ['fundamentals'],
    concept: 'Separate inputs, outputs, and side effects using explicit function contracts.',
    intuition: 'A function should accept what it needs and return what its caller needs.',
    example:
      'def subtotal(price, quantity): return price * quantity. A separate caller validates input and persists the order. Returning a value keeps calculations independently testable.',
    checks: [
      [
        'Which statement sends a function result to its caller?',
        'return total',
        'print(total)',
        'total == 0',
        'return delivers a value; print writes output.',
      ],
      [
        'A local variable is set inside a function. Where should callers get it?',
        'From an explicit return value',
        'By reading the local name globally',
        'By using eval',
        'Locals belong to their invocation; expose results explicitly.',
      ],
      [
        'Which signature best isolates a discount calculation?',
        'discounted_total(total, rate)',
        'calculate_everything() reading global state',
        'discounted_total() that writes a database row',
        'Explicit inputs allow deterministic tests without unrelated side effects.',
      ],
      [
        'Two imports need the same price rule. How should you refactor?',
        'Extract one pure price function and call it from both workflows',
        'Duplicate it to avoid function overhead',
        'Put printing, SQL, and pricing into one function',
        'A shared pure rule eliminates divergent copies and supports direct testing.',
      ],
    ],
  },
  {
    key: 'structures',
    name: 'Lists, dictionaries & sets',
    category: 'Data structures',
    prerequisites: ['fundamentals'],
    concept: 'Choose containers by ordering, lookup, and uniqueness needs.',
    intuition:
      'Lists keep sequence; dictionaries associate keys with values; sets remove duplicates.',
    example:
      'seen = set(); totals = {}. For each order ID, skip it if already seen; otherwise add the ID and update totals[customer]. Keep a separate list if output order matters.',
    checks: [
      [
        'Which container stores customer ID → balance?',
        'dict',
        'list of unlabelled numbers',
        'set of balances',
        'A dictionary associates stable keys with their values.',
      ],
      [
        'Which container directly enforces unique SKU strings?',
        'set',
        'list',
        'tuple with duplicates',
        'A set represents unique elements.',
      ],
      [
        'How do you read an optional dictionary key safely?',
        'row.get("note")',
        'row["note"] always',
        'row.note',
        'get permits absent keys; indexing raises KeyError.',
      ],
      [
        'Need ordered invoices plus fast ID lookup. Choose a design.',
        'Keep an ordered list and an ID-keyed dictionary with consistent updates',
        'Use an unordered set only',
        'Search a string containing all IDs',
        'Separate sequence and lookup structures serve distinct requirements.',
      ],
    ],
  },
  {
    key: 'comprehensions',
    name: 'Iteration & comprehensions',
    category: 'Data structures',
    prerequisites: ['structures'],
    concept: 'Transform and filter collections clearly without unsafe mutation during iteration.',
    intuition:
      'Build the new collection from the old one rather than removing items while walking it.',
    example:
      'valid = [r for r in rows if r["quantity"] > 0]. This keeps the original rows for a rejection report and avoids skipping items during removal.',
    checks: [
      [
        'What is [x * 2 for x in [1, 3]]?',
        '[2, 6]',
        '[1, 3, 2]',
        '[3, 5]',
        'The expression transforms each input value once.',
      ],
      [
        'Which keeps positive amounts?',
        '[x for x in amounts if x > 0]',
        '[x > 0 for x in amounts]',
        'amounts.remove(0) while looping',
        'The trailing condition filters, rather than producing booleans.',
      ],
      [
        'Need one output per dictionary pair. What iteration exposes both?',
        'mapping.items()',
        'mapping.keys() only',
        'range(mapping)',
        'items provides key/value pairs.',
      ],
      [
        'A long comprehension sends network requests and handles failures. Improve it.',
        'Use a named loop with explicit error handling',
        'Nest more comprehensions',
        'Ignore failures to keep one line',
        'Complex side effects deserve explicit flow, not compressed syntax.',
      ],
    ],
  },
  {
    key: 'modules',
    name: 'Modules, packages & environments',
    category: 'Python foundations',
    prerequisites: ['functions'],
    concept: 'Organize imports and isolate reproducible dependencies.',
    intuition:
      'Import should define reusable behavior; running a command should trigger side effects deliberately.',
    example:
      'Put CSV helpers in imports.py, guard command execution with if __name__ == "__main__", and install pinned dependencies in a project virtual environment.',
    checks: [
      [
        'What makes a module reusable without executing its CLI on import?',
        'An if __name__ == "__main__" guard',
        'A top-level main() call',
        'A print in every function',
        'The guard limits command execution to direct invocation.',
      ],
      [
        'Why use a virtual environment?',
        'Isolate project dependencies',
        'Encrypt every Python file',
        'Replace source control',
        'Dependency isolation avoids project version conflicts.',
      ],
      [
        'An import requests.py shadows the HTTP library. Best correction?',
        'Rename the local file and update imports',
        'Install the library repeatedly',
        'Catch ImportError forever',
        'Local module names can shadow dependencies.',
      ],
      [
        'A teammate cannot reproduce a build. What should you commit?',
        'Dependency version manifest and setup instructions, excluding the environment directory',
        'Your entire machine environment',
        'Only screenshots of installed packages',
        'A declared reproducible dependency set works across machines.',
      ],
    ],
  },
  {
    key: 'oop',
    name: 'Classes & composition',
    category: 'Design',
    prerequisites: ['functions'],
    concept:
      'Model state with classes, protect invariants, and choose inheritance or composition deliberately.',
    intuition:
      'Use objects when state and behavior belong together; inject collaborators rather than hiding them.',
    example:
      'OrderService receives a repository in its constructor. submit() validates an order then asks that repository to save it. A test can pass a fake repository without real SQL.',
    checks: [
      [
        'Where should per-instance order state live?',
        'On self in the constructor',
        'In a shared mutable class list',
        'In a global variable',
        'Instance attributes separate each object’s state.',
      ],
      [
        'A mail sender is a collaborator of a service. Prefer?',
        'Pass the sender into the service',
        'Subclass the sender to become the service',
        'Hardcode a network call in every method',
        'Composition separates responsibilities and permits replacement.',
      ],
      [
        'A specialized repository honors the same repository contract. When is inheritance appropriate?',
        'When it preserves the base is-a contract; use composition for independent collaborators',
        'Whenever two classes share a field name',
        'To make a service into a database connection',
        'Inheritance requires substitutable behavior; composition models a collaborator. Validated methods still protect object invariants.',
      ],
      [
        'A test must avoid live billing. Choose the design.',
        'Inject a fake billing client implementing the needed methods',
        'Inherit all billing internals into the service',
        'Use the real client and refund later',
        'A narrow injected collaborator makes the service safely testable.',
      ],
    ],
  },
  {
    key: 'exceptions',
    name: 'Exceptions & defensive programming',
    category: 'Reliability',
    prerequisites: ['functions'],
    concept: 'Validate external inputs and handle expected failures without masking defects.',
    intuition: 'Catch the error you can meaningfully handle; keep unexpected failures visible.',
    example:
      'try: quantity = int(raw) except ValueError: return a validation error. A database outage should not be converted into a successful order.',
    checks: [
      [
        'Which conversion may raise ValueError?',
        'int("three")',
        'len("three")',
        'str(3)',
        'The text does not represent an integer.',
      ],
      [
        'What should except Exception: pass be replaced with?',
        'Specific handling or explicit propagation and logging',
        'A larger try block',
        'A success response',
        'Silencing every failure hides defects and false success.',
      ],
      [
        'Before calculating a price from external JSON, do what?',
        'Check required fields, types, and allowed ranges',
        'Trust every JSON value',
        'Use eval on the JSON',
        'Valid syntax does not imply valid business data.',
      ],
      [
        'A timeout occurs after sending a charge. What should the service do?',
        'Record uncertainty and reconcile using an idempotency key',
        'Retry unlimited times without a key',
        'Report successful payment unconditionally',
        'An unknown outcome requires reconciliation to avoid double charging.',
      ],
    ],
  },
  {
    key: 'files',
    name: 'Files, JSON & CSV',
    category: 'Integration',
    prerequisites: ['exceptions'],
    concept:
      'Read structured files with managed resources, explicit encodings, and schema validation.',
    intuition: 'Parsing structure is different from validating meaning.',
    example:
      'with open(path, encoding="utf-8", newline="") as f: rows = list(csv.DictReader(f)). Convert amount strings deliberately and report rejected row numbers.',
    checks: [
      [
        'Why use with open(...)?',
        'Close resources even when processing raises',
        'Make every file read-only',
        'Guarantee valid JSON',
        'A context manager handles cleanup on exit.',
      ],
      [
        'A CSV field contains a quoted comma. Parse with?',
        'csv.DictReader',
        'line.split(",")',
        'eval(line)',
        'The CSV parser respects quoting and escaping.',
      ],
      [
        'json.loads returns an amount "12.50". Next step?',
        'Validate and convert using the chosen money representation',
        'Assume it is already a float',
        'Concatenate it with the total',
        'JSON strings remain strings after parsing.',
      ],
      [
        'An import has valid and malformed rows. Design a recoverable workflow.',
        'Validate rows, preserve line numbers, and write accepted/rejected summaries',
        'Overwrite the original file before validation',
        'Ignore malformed rows without reporting',
        'Explicit rejection records support correction and auditability.',
      ],
    ],
  },
  {
    key: 'debugging',
    name: 'Tracebacks & edge-case debugging',
    category: 'Reliability',
    prerequisites: ['fundamentals', 'exceptions'],
    concept: 'Reproduce failures and locate the first incorrect assumption using stack traces.',
    intuition:
      'A trace identifies where an error surfaced; inspect the values that reached that line.',
    example:
      'KeyError: customer_id at process(row) means that key is absent. Reproduce with an incomplete row, then decide whether the contract requires rejection or an optional value.',
    checks: [
      [
        'KeyError on row["sku"] most directly suggests?',
        'The key is absent',
        'The CPU is too slow',
        'The value is always zero',
        'Dictionary indexing raises when the key is missing.',
      ],
      [
        'Which test best reproduces division by zero in an average?',
        'An empty list',
        'A list of positive values',
        'A sorted list of ten values',
        'The denominator len(values) becomes zero.',
      ],
      [
        'A traceback points to a helper. Where should you investigate?',
        'The failing line and caller-provided input',
        'Only reinstall Python',
        'Every unrelated module first',
        'Trace the actual values and violated assumptions.',
      ],
      [
        'A production bug cannot be reproduced with normal orders. Next step?',
        'Create a minimal failing input from sanitized logs and add a regression test',
        'Rewrite the whole service immediately',
        'Remove the failing exception',
        'Minimal reproduction narrows the cause and guards the repair.',
      ],
    ],
  },
  {
    key: 'testing',
    name: 'Assertions & unit tests',
    category: 'Reliability',
    prerequisites: ['functions', 'debugging'],
    concept: 'Verify behavior, boundaries, and failure paths with isolated tests.',
    intuition: 'Tests should demonstrate the contract independently of the implementation.',
    example:
      'assert subtotal(10, 2) == 20; test zero quantities and rejection of negatives. Fake the repository to verify rejected orders never call save().',
    checks: [
      [
        'What does assert actual == expected verify?',
        'A behavioral expectation',
        'That the function has a particular name',
        'Every possible input',
        'An assertion checks one specific expected outcome.',
      ],
      [
        'Which makes a unit test deterministic?',
        'Inject a fixed clock and fake HTTP client',
        'Use live network and current time',
        'Retry until green',
        'Control external variability at dependency boundaries.',
      ],
      [
        'A bug affects empty inputs. What belongs in the regression test?',
        'The empty input and expected result or error',
        'Only a normal input',
        'The exact source code as expected text',
        'Regression tests encode observed failure behavior.',
      ],
      [
        'Which test set best validates an order repair?',
        'Valid order, missing SKU, zero/negative quantity, and repository failure',
        'Only constructor creation',
        'Only a large successful batch',
        'Boundary and failure tests protect both validation and side-effect behavior.',
      ],
    ],
  },
  {
    key: 'http',
    name: 'HTTP, REST & JSON contracts',
    category: 'Integration',
    prerequisites: ['exceptions', 'files'],
    concept: 'Respect API status codes, timeouts, schemas, and retry boundaries.',
    intuition: 'A transport response and a valid business result are separate checks.',
    example:
      'client.get(url, timeout=5); check status before decoding JSON, then validate required fields. Retry a transient GET with bounded backoff; do not retry an uncertain payment blindly.',
    checks: [
      [
        'What does HTTP 404 usually indicate?',
        'Requested resource not found',
        'Successful creation',
        'Client timeout',
        '404 describes a missing resource, not a network timeout.',
      ],
      [
        'Why set a request timeout?',
        'Bound waiting for an unavailable dependency',
        'Guarantee a 200 response',
        'Disable JSON validation',
        'A timeout limits how long a worker can be occupied.',
      ],
      [
        '200 with malformed JSON should become?',
        'An integration error with context',
        'A valid empty result automatically',
        'A silently cached success',
        'Success status does not guarantee valid response content.',
      ],
      [
        'A rate-limited GET returns 429 and Retry-After. Best policy?',
        'Respect the delay with bounded retries and surface exhaustion',
        'Busy-loop forever',
        'Retry every payment POST identically without a key',
        'Honor the server’s backpressure and bound resource use.',
      ],
    ],
  },
  {
    key: 'sql',
    name: 'SQL & parameterized queries',
    category: 'Integration',
    prerequisites: ['structures'],
    concept: 'Retrieve and update backend data using parameter binding and transaction boundaries.',
    intuition: 'Values belong in parameters; SQL structure belongs in trusted code.',
    example:
      'cursor.execute("SELECT id FROM orders WHERE customer_id = ?", (customer_id,)). Parameter binding keeps quoted customer input out of SQL syntax.',
    checks: [
      [
        'Which query safely handles an external ID?',
        'WHERE id = ? with a bound parameter',
        'f"WHERE id = {external_id}"',
        'Concatenating quoted input',
        'Binding treats input as data rather than executable SQL.',
      ],
      [
        'What filters rows before aggregation?',
        'WHERE',
        'ORDER BY',
        'SELECT alone',
        'WHERE applies a row predicate.',
      ],
      [
        'Two writes must succeed together. Use?',
        'One transaction with rollback on failure',
        'Separate unconditional commits',
        'An exception handler that reports success',
        'Transactions prevent partially applied business changes.',
      ],
      [
        'A transfer debits then credits. How should failure be handled?',
        'Roll back both updates and report failure',
        'Keep the debit if credit fails',
        'Concatenate account IDs into SQL',
        'Atomic updates preserve the transfer invariant.',
      ],
    ],
  },
  {
    key: 'quality',
    name: 'Readability & refactoring',
    category: 'Design',
    prerequisites: ['functions'],
    concept: 'Improve structure while preserving behavior and meaningful names.',
    intuition: 'Refactor behind a behavioral safety net; make responsibilities easy to name.',
    example:
      'Split load_rows(), validate_row(), compute_invoice(), and write_report(). Keep golden input/output fixtures so extraction cannot silently change totals.',
    checks: [
      [
        'Which name states purpose?',
        'calculate_shipping_cost',
        'do_stuff',
        'x1',
        'Intent-revealing names reduce guesswork.',
      ],
      [
        'What should remain stable during a refactor?',
        'Observable behavior covered by tests',
        'The number of source lines',
        'Every local variable name',
        'Refactoring changes structure without changing the contract.',
      ],
      [
        'Two blocks implement the same rule. Prefer?',
        'One named function with explicit inputs',
        'Copy again for safety',
        'A global mutable result',
        'Consolidation reduces inconsistent future edits.',
      ],
      [
        'A script mixes network, validation, and calculations. Safest first step?',
        'Capture current behavior in tests, then extract pure calculations',
        'Rewrite all dependencies at once',
        'Delete validation to shorten it',
        'Small verified changes limit regression risk.',
      ],
    ],
  },
  {
    key: 'reasoning',
    name: 'Problem solving & complexity',
    category: 'Workplace reasoning',
    prerequisites: ['structures'],
    concept: 'Choose simple algorithms by correctness constraints and expected input size.',
    intuition: 'State the invariant, then consider repeated work as inputs grow.',
    example:
      'For 10,000 orders, build a set of blocked IDs once and test membership per row instead of scanning a list repeatedly. Preserve the required output order separately.',
    checks: [
      [
        'Scanning n rows once is approximately?',
        'O(n)',
        'O(1) always',
        'O(n squared) always',
        'One visit per input grows linearly.',
      ],
      [
        'Repeated membership checks usually benefit from?',
        'A set or dictionary',
        'Nested list scans',
        'Converting every ID to an image',
        'Hash containers usually provide expected constant-time lookup.',
      ],
      [
        'When choosing an algorithm, establish first?',
        'Correctness requirements and expected sizes',
        'Shortest possible line count',
        'Largest available library',
        'Requirements determine what a valid solution must preserve.',
      ],
      [
        'Need first-seen unique IDs from a large stream. Choose?',
        'A seen set plus ordered output list',
        'Sort all IDs and lose first-seen order',
        'Nested scans for each new ID',
        'The set avoids repeated linear scans while the list preserves order.',
      ],
    ],
  },
  {
    key: 'clarification',
    name: 'Requirement clarification',
    category: 'Workplace skills',
    prerequisites: [],
    concept:
      'Resolve ambiguous contracts, edge cases, and acceptance criteria before implementing.',
    intuition: 'Ask for examples that would distinguish two plausible interpretations.',
    example:
      'Before importing customers, ask whether a repeated ID is an update, rejection, or duplicate to skip. Record that decision and the expected result for a repeated row.',
    checks: [
      [
        '“Skip bad records” is ambiguous. Best question?',
        'Which failures count as bad, and how should rejections be reported?',
        'Which editor should I use?',
        'Can I remove all error handling?',
        'Clarify behavior that affects correctness and user expectations.',
      ],
      [
        'Who should confirm a changed duplicate policy?',
        'The stakeholder responsible for the contract',
        'Any unrelated developer',
        'Nobody if tests pass',
        'Policy decisions need an accountable owner.',
      ],
      [
        'Which acceptance criterion is testable?',
        'Repeated order ID creates no second charge and returns the original receipt',
        'Make duplicates better',
        'Use clean code',
        'Observable outcomes can be checked directly.',
      ],
      [
        'A deadline blocks one business decision. Best response?',
        'Document an assumption, isolate the policy, and request confirmation while progressing elsewhere',
        'Invent the policy and hide it',
        'Stop every independent task',
        'Visible, reversible assumptions let work continue without pretending certainty.',
      ],
    ],
  },
  {
    key: 'communication',
    name: 'Technical communication',
    category: 'Workplace skills',
    prerequisites: ['clarification'],
    concept: 'Explain evidence, impact, tradeoffs, and next steps to stakeholders.',
    intuition:
      'Lead with the user impact, support it with evidence, and name what remains uncertain.',
    example:
      '“Missing SKU rows caused the import to stop. The fix rejects those rows with line numbers; 18 of 20 imported in staging. We still need the duplicate-ID policy confirmed.”',
    checks: [
      [
        'Which bug update is actionable?',
        'The importer rejects missing SKU rows; staging tests cover them; rollout is pending',
        'It is fixed somehow',
        'Python is broken',
        'Impact, evidence, and next step make the update useful.',
      ],
      [
        'A test passed locally. What can you claim?',
        'That the tested cases passed in that environment',
        'That production can never fail',
        'That every requirement is proven',
        'Scope conclusions to observed evidence.',
      ],
      [
        'How should you explain a retry tradeoff?',
        'Retries improve transient recovery but need bounds and idempotency to avoid duplicate effects',
        'Retries are always free',
        'Never mention risks',
        'State both benefit and operational consequence.',
      ],
      [
        'Stakeholder asks whether the release is ready after a partial outage test. Respond?',
        'Report passed cases, the untested outage risk, and a concrete validation plan',
        'Promise flawless production',
        'Send only a stack trace',
        'Transparent limits support an informed release decision.',
      ],
    ],
  },
  {
    key: 'validation',
    name: 'Backend validation & service boundaries',
    category: 'Design',
    prerequisites: ['oop', 'http'],
    concept:
      'Separate transport parsing, domain rules, and persistence without trusting client input.',
    intuition:
      'Validate at the boundary, keep business rules central, and persist only accepted state.',
    example:
      'A handler parses JSON and returns 400 for bad types. OrderService checks stock and quantity. OrderRepository performs parameterized SQL. Each layer can be tested independently.',
    checks: [
      [
        'Where should JSON request shape be checked?',
        'At the request boundary',
        'Only after committing',
        'In the browser alone',
        'Server-side boundary validation prevents malformed data reaching domain logic.',
      ],
      [
        'Who should own an order quantity business rule?',
        'The domain/service layer',
        'Every HTML button separately',
        'Only the database driver',
        'Central rules remain consistent across transport entry points.',
      ],
      [
        'Which dependency direction keeps a service testable?',
        'Service uses an injected repository interface',
        'Service constructs a production database globally',
        'Repository controls HTTP routing',
        'An injected persistence boundary permits isolated service tests.',
      ],
      [
        'API and CSV import share a rule. Best architecture?',
        'Both call the same validated domain operation through separate adapters',
        'Duplicate the rule in each parser',
        'Permit imports to bypass validation',
        'Shared domain behavior avoids transport-specific inconsistencies.',
      ],
    ],
  },
];
