import type { Simulation } from '../types';
import { task } from './authoring';
type Decision = [string, string, string, string, string, string, string[]];
function scenario(
  id: string,
  title: string,
  stakeholder: string,
  stakeholderRole: string,
  brief: string,
  data: string,
  decisions: Decision[],
): Simulation {
  const phases = [
    'Clarify',
    'Inspect',
    'Trace',
    'Decide',
    'Implement',
    'Validate',
    'Test',
    'Brief',
  ];
  return {
    id,
    title,
    stakeholder,
    stakeholderRole,
    company: 'BridgeWorks · fictional',
    brief,
    data,
    items: decisions.map(([prompt, context, good, bad, worse, explanation, keys], i) =>
      task(
        `${id}-${i + 1}`,
        phases[i],
        prompt,
        context,
        [good, bad, worse],
        explanation,
        'py',
        keys,
        i === 0
          ? [
              `Thanks for checking. ${data} We will use that contract for the remaining decisions.`,
              `We still need a clear contract. ${data} Please use these requirements for the remaining decisions.`,
            ]
          : undefined,
      ),
    ),
  };
}
export const pythonDiagnostic = [
  scenario(
    'py-d-orders',
    'Repair the order processor',
    'Nisha',
    'Operations manager',
    'Some orders crash the nightly run, and total revenue looks too high. Choose a repair that preserves the order contract.',
    `Contract: quantity must be a positive integer; missing SKU is rejected with its row number. Repeated order IDs are skipped after the first valid row. A rejected row must not stop the batch. Prices are integer paise.\nRows: A/pen/2 at 500; B/pen/0 at 500; A/pen/2 at 500; C/(missing SKU)/1. Expected accepted total: 1000 paise.\nCurrent code:\ntotal = 0\nseen = []\nfor row in rows:\n  if row['quantity']:\n    total += row['price'] * row['quantity']\n  print(row['sku'].upper())`,
    [
      [
        'What should you clarify with Nisha first?',
        'The stakeholder wants crashes fixed without changing billing.',
        'Confirm quantity rules, duplicate IDs, and rejected-row reporting',
        'Ask whether the editor should use dark mode',
        'Promise to suppress every exception',
        'The contract determines validation and billing correctness.',
        ['clarification', 'communication'],
      ],
      [
        'Which row policy should the loop enforce?',
        'The code uses if row["quantity"].',
        'Require an integer quantity > 0 before adding to total',
        'Accept any truthy quantity, including -2',
        'Convert every quantity to its absolute value',
        'Truthiness does not enforce a positive quantity and treats negative values as valid.',
        ['fundamentals', 'exceptions'],
      ],
      [
        'A KeyError occurs on row["sku"]. What is the useful diagnosis?',
        'Row C has no sku key.',
        'Missing required input reached direct dictionary indexing',
        'The loop needs more CPU',
        'upper() always raises KeyError',
        'The key is missing before upper runs; reject the row under the contract.',
        ['debugging', 'structures'],
      ],
      [
        'How should duplicate detection work?',
        'There may be 50,000 rows; arrival order matters.',
        'Use a seen-ID set, adding only accepted IDs, and keep ordered results separately',
        'Scan all prior rows for every input',
        'Use a set of prices as the duplicate key',
        'A set makes ID membership efficient; only valid accepted IDs establish duplicates.',
        ['structures', 'reasoning'],
      ],
      [
        'Which extraction makes totals testable?',
        'Printing and billing currently share one loop.',
        'A pure line_total(price, quantity) function used after validation',
        'A global total updated by every imported module',
        'A function that also opens the database and prints reports',
        'Explicit inputs and returned values isolate calculations and reduce side effects.',
        ['functions', 'quality'],
      ],
      [
        'How should an invalid row affect the batch?',
        'Rejection reporting is part of the agreed contract.',
        'Record its row number and reason; continue with other valid rows',
        'Catch every exception and label the row successful',
        'Abort on the first expected validation failure',
        'Handle expected invalid input explicitly while keeping unexpected defects visible.',
        ['exceptions', 'validation'],
      ],
      [
        'Which tests best protect this repair?',
        'The four-row sample must total 1000 paise.',
        'Valid quantity, zero/negative quantity, missing SKU, repeated ID, and exact accepted total',
        'Only check that the script prints something',
        'Use only valid rows and assert no crash',
        'Boundary tests protect both the aggregate and rejection behavior.',
        ['testing', 'debugging'],
      ],
      [
        'What should the release brief say?',
        'The sample and regression tests passed; production rollout is pending.',
        'The batch now rejects invalid rows and skips duplicate IDs; sample total is 1000 paise; staging rollout remains',
        'Revenue is guaranteed correct for every future order',
        'We hid the errors so there is no risk',
        'State observed evidence and remaining validation without overstating readiness.',
        ['communication', 'reasoning'],
      ],
    ],
  ),
  scenario(
    'py-d-api',
    'Integrate a supplier API',
    'Omar',
    'Product owner',
    'The supplier endpoint is flaky. Inventory imports sometimes report success despite empty or malformed responses.',
    `GET /stock returns JSON {"items":[{"sku":"P1","quantity":4}]}. Quantity is a non-negative integer; zero stock is valid. A 429 response includes Retry-After. Set a 5-second timeout and at most 2 retries for transient GET failures. Never overwrite inventory on an invalid response. SQL values must be bound.\nCurrent client: response = requests.get(url); payload = response.json(); save(payload).\nCurrent query: "UPDATE stock SET quantity=" + str(qty) + " WHERE sku='" + sku + "'"`,
    [
      [
        'Which contract question is most useful?',
        'Supplier data will overwrite local stock.',
        'Confirm schema, zero-stock semantics, retry limits, and invalid-response policy',
        'Ask for the supplier logo',
        'Assume any JSON should overwrite stock',
        'Import success needs explicit transport, schema, and persistence acceptance criteria.',
        ['clarification', 'http'],
      ],
      [
        'Choose the network call policy.',
        'The endpoint may stall or return 429.',
        'Use a timeout, check status, honor Retry-After, and bound GET retries',
        'Retry forever with no delay',
        'Decode all bodies before inspecting status',
        'Bound waiting and retries; status determines whether the body represents a valid result.',
        ['http', 'exceptions'],
      ],
      [
        'Why does if not item.get("quantity") reject valid data?',
        'An item has quantity 0.',
        'It conflates zero stock with a missing value',
        'JSON cannot represent zero',
        'get always raises for missing keys',
        'Validate absence and type separately from a legitimate zero value.',
        ['fundamentals', 'debugging'],
      ],
      [
        'Which validation should precede saving?',
        '200 OK contains items with one quantity="many".',
        'Validate object/list structure, required fields, integer types, and non-negative ranges',
        'Accept because the HTTP status is 200',
        'Use eval to convert the payload',
        'HTTP success and parse success do not establish a valid domain record.',
        ['files', 'validation'],
      ],
      [
        'How should the save query be written?',
        'SKU input may include a quote.',
        'UPDATE stock SET quantity=? WHERE sku=? with bound values',
        'Concatenate quoted SKU text into SQL',
        'Strip all quotes and build SQL text',
        'Parameter binding protects query structure and preserves legitimate values.',
        ['sql', 'exceptions'],
      ],
      [
        'How should the client be organized?',
        'Tests need deterministic supplier results.',
        'Inject a supplier client into an inventory service and a repository for saving',
        'Make every service method call a global live requests client',
        'Subclass the SQL connection as the HTTP handler',
        'Composition separates integration and persistence so each can be replaced in tests.',
        ['oop', 'functions'],
      ],
      [
        'Which integration-unit test set is strongest?',
        'The client should handle partial dependency failure.',
        'Fake timeout, 429, malformed JSON, invalid quantity, zero stock, and valid save behavior',
        'Only call the real supplier once',
        'Assert the client class name',
        'Controllable fakes test failure policy and prevent incorrect persistence.',
        ['testing', 'http'],
      ],
      [
        'How should you summarize the tradeoff?',
        'Retry handling is implemented; production supplier behavior remains unverified.',
        'Bounded retries improve transient recovery; invalid data cannot overwrite stock; live monitoring remains',
        'Retries guarantee the supplier will always work',
        'A 200 status proves every stock value is right',
        'Explain benefits, safeguards, and limits of the verified evidence.',
        ['communication', 'reasoning'],
      ],
    ],
  ),
  scenario(
    'py-d-refactor',
    'Refactor the dispatch script',
    'Priya',
    'Team lead',
    'A script mixes file loading, duplicate filtering, totals, SQL, and printing. Make it easier to change without breaking dispatch output.',
    `Input is UTF-8 CSV with columns order_id,customer_id,amount_paise. Quoted commas can appear in customer notes. First accepted order ID wins; output preserves arrival order. Reject malformed or negative amounts with line numbers. Existing sample: X/7/100, Y/7/200, X/7/100 → customer 7 total 300. Importing the helper module must not execute a dispatch.\nCurrent conceptual script:\nrows = list(csv.DictReader(open(path)))\nfor row in rows:\n  totals[row['customer_id']] = totals.get(row['customer_id'], 0) + int(row['amount_paise'])\n  conn.execute("INSERT INTO dispatch VALUES ('" + row['order_id'] + "')")\n  print(row['customer_id'], totals[row['customer_id']])\nmain()`,
    [
      [
        'What should you confirm before refactoring?',
        'The team asks for cleaner code while retaining output.',
        'Confirm preserved outputs, duplicate rules, and rejection reporting with a sample',
        'Change duplicate policy to simplify the code',
        'Choose inheritance before understanding behavior',
        'A behavioral contract supplies the safety net for refactoring.',
        ['clarification', 'quality'],
      ],
      [
        'Which CSV loading approach is appropriate?',
        'Notes may contain commas; encoding is UTF-8.',
        'with open(..., encoding="utf-8", newline="") and csv.DictReader',
        'Split each line on every comma',
        'Read bytes and eval each row',
        'Managed resources and a CSV parser handle quoted structure correctly.',
        ['files', 'exceptions'],
      ],
      [
        'Which extraction preserves a clear responsibility?',
        'load_and_save() currently performs every task.',
        'Separate load_rows, validate_row, aggregate_totals, and write_report',
        'Put everything into one large class method',
        'Move each statement into an unrelated function',
        'Cohesive named units separate I/O from domain work and are directly testable.',
        ['functions', 'quality'],
      ],
      [
        'Choose grouping and duplicate containers.',
        'Need customer totals, ID membership, and ordered accepted rows.',
        'Dictionary of totals, set of accepted IDs, and list of accepted rows',
        'One list repeatedly rescanned for both lookups',
        'A set of amounts as the only storage',
        'Different structures directly express the required associations, uniqueness, and ordering.',
        ['structures', 'reasoning'],
      ],
      [
        'Which transformation is safe?',
        'Need valid rows while retaining rejected evidence.',
        'Build a new list with a clear validation predicate; do not remove source rows while iterating',
        'Remove every bad row directly during traversal',
        'Use a nested comprehension that writes SQL',
        'Pure filtering preserves source evidence and avoids mutation hazards.',
        ['comprehensions', 'validation'],
      ],
      [
        'How should command execution be separated?',
        'A test imports dispatch helpers.',
        'Guard CLI execution with if __name__ == "__main__" and declare dependencies in a project environment',
        'Call main() at the top of the module',
        'Ask tests never to import helpers',
        'Import should expose definitions without triggering dispatch; declared dependencies make setup reproducible.',
        ['modules', 'functions'],
      ],
      [
        'What validates behavior after extraction?',
        'The first-seen sample must still total 300 for customer 7.',
        'Golden sample output, quoted CSV, duplicates, malformed amount, and import-without-side-effects tests',
        'Count the new number of functions',
        'Run only a style formatter',
        'Tests should protect the observable contract and side-effect boundary.',
        ['testing', 'files'],
      ],
      [
        'What should the handoff communicate?',
        'The refactor passed the stated fixtures.',
        'The script now separates parsing, rules, and output; fixtures match; large-file performance still needs measurement',
        'All performance problems are solved because code is shorter',
        'Only send the new folder names',
        'Connect structural changes to tested behavior and explicitly state unmeasured performance.',
        ['communication', 'quality'],
      ],
    ],
  ),
];
export const pythonReassessment = [
  scenario(
    'py-r-logs',
    'Build a recoverable log importer',
    'Esha',
    'Reliability engineer',
    'A log import stops when it meets a malformed record. Recover valid events and keep an actionable rejection trail.',
    `Input is UTF-8 JSON Lines, one object per line: {"event_id":"E1","latency_ms":0}. latency_ms must be an integer >= 0. First valid event ID wins; invalid lines must include their original line number in a rejection file. For E1/0, E2/20, E1/5, malformed JSON: accept 2 events, total latency 20. The command must not run when imported.`,
    [
      [
        'What do you ask before implementation?',
        'The request says recover as much as possible.',
        'Confirm malformed-line handling, duplicate key, zero latency, and expected outputs',
        'Ask whether logs should use a different font',
        'Assume all failures should be hidden',
        'Concrete acceptance criteria determine recovery and reporting.',
        ['clarification', 'communication'],
      ],
      [
        'Which parser structure respects the format?',
        'Each line is a separate JSON document.',
        'Read with a managed UTF-8 file and json.loads each line with its number',
        'json.loads the whole file as one object',
        'Split lines into fields on commas',
        'JSON Lines needs individual parsing with original position retained.',
        ['files', 'exceptions'],
      ],
      [
        'What is wrong with if event["latency_ms"]?',
        'A valid event has latency 0.',
        'It treats zero as false instead of validating presence, integer type, and range',
        'Zero cannot be represented in JSON',
        'It proves the event is duplicated',
        'Zero is valid; explicit schema checks preserve it.',
        ['fundamentals', 'debugging', 'validation'],
      ],
      [
        'How should events be deduplicated?',
        'Arrival order matters; only valid IDs should establish a duplicate.',
        'Seen-ID set plus ordered accepted list; add IDs after validation',
        'Deduplicate by latency value',
        'Sort first and pick arbitrary records',
        'The contract defines identity and first-valid order, while a set avoids repeated scans.',
        ['structures', 'reasoning'],
      ],
      [
        'Which processing unit is easiest to test?',
        'The importer needs an accepted list and rejection report.',
        'A pure validate_event function returning a record or reason, composed by the file adapter',
        'A global function that opens files and modifies all state',
        'A broad except that returns success',
        'Explicit results isolate policy from file side effects.',
        ['functions', 'quality'],
      ],
      [
        'Choose module packaging and filtering behavior.',
        'A scheduler and a test both import the module.',
        'Guard command execution; use a clear loop for rejection side effects and a comprehension only for pure projections',
        'Run the import on module load and mutate the input list',
        'Put all rejection writes in a nested comprehension',
        'Import-safe modules and clear side-effect flow improve reuse and reliability.',
        ['modules', 'comprehensions'],
      ],
      [
        'Which tests protect recovery?',
        'Expected accepted count is 2 and total latency is 20.',
        'Zero latency, malformed JSON, duplicate IDs, missing key, and preserved line numbers',
        'Only a normal event',
        'Only check the rejection filename',
        'Test both successful recovery and traceable failure behavior.',
        ['testing', 'exceptions'],
      ],
      [
        'How should you report completion?',
        'Fixtures pass; very large files have not been load tested.',
        'Two valid events survive the sample, rejections include line numbers, and load testing remains',
        'Every future log is guaranteed valid',
        'There are no errors because exceptions are caught',
        'Report observed output and the remaining performance limit.',
        ['communication', 'reasoning'],
      ],
    ],
  ),
  scenario(
    'py-r-inventory',
    'Implement an inventory reservation API',
    'Ravi',
    'Backend lead',
    'Reservations sometimes double-decrement stock after retries. Design a safe request path and verify its failure behavior.',
    `POST /reservations receives request_id,sku,quantity (positive integer). A repeated request_id returns the original reservation without another decrement. Missing SKU returns validation failure. Persist reservation and stock decrement atomically with parameterized SQL. An external stock GET has a 3-second timeout; malformed JSON or 503 means no reservation is committed.`,
    [
      [
        'Which requirement must be clarified first?',
        'A caller may retry after losing the response.',
        'Confirm request-ID idempotency and atomic stock/reservation behavior',
        'Ask which endpoint name is shortest',
        'Assume every retry is a new reservation',
        'Idempotency and atomicity determine whether retries can double-decrement stock.',
        ['clarification', 'http'],
      ],
      [
        'What request validation is appropriate?',
        'JSON may omit fields or include quantity=-1.',
        'Validate required keys, expected types, and quantity > 0 before domain work',
        'Trust it because JSON parsed',
        'Coerce negative quantities to positive',
        'Parsing does not validate a reservation contract.',
        ['files', 'validation', 'fundamentals'],
      ],
      [
        'A test sees stock decremented twice. What should you investigate?',
        'Both requests have the same request_id.',
        'Whether the service checks and persists the idempotency key atomically',
        'Whether the SKU text is uppercase',
        'Whether printing is disabled',
        'The duplicate operation is a state/transaction issue, not formatting.',
        ['debugging', 'structures'],
      ],
      [
        'How should stock and reservation writes be saved?',
        'Either both must persist or neither should.',
        'Use bound parameters in one transaction and rollback on failure',
        'Commit stock before inserting reservation',
        'Concatenate the request fields into SQL',
        'Atomic bound writes preserve stock and prevent injection.',
        ['sql', 'exceptions'],
      ],
      [
        'Which design supports an isolated service test?',
        'Live database and supplier calls should not be required.',
        'Inject repository and stock client collaborators into ReservationService',
        'Create global live clients inside each method',
        'Inherit a SQL connection to implement HTTP handling',
        'Composition exposes controllable dependency boundaries.',
        ['oop', 'functions'],
      ],
      [
        'What if the supplier returns 503 or malformed JSON?',
        'The contract says no commit on upstream failure.',
        'Return a controlled dependency failure, respect bounded retry policy, and leave local state unchanged',
        'Commit with guessed stock',
        'Return success with empty reservation',
        'Failure policy must prevent unsupported local state changes.',
        ['http', 'exceptions'],
      ],
      [
        'Which test set is adequate?',
        'Reproducing retry behavior is central.',
        'Valid reservation, duplicate key, invalid quantity, timeout, malformed JSON, and rollback after second-write failure',
        'Only the happy-path response',
        'Only an HTTP status check without state assertions',
        'Verify response and persistence invariants under boundary and dependency failures.',
        ['testing', 'sql'],
      ],
      [
        'What should the implementation brief emphasize?',
        'Unit tests pass; live concurrency validation remains.',
        'Retry uses the same request ID; writes are atomic; failure tests pass; concurrent-load checks remain',
        'Retries can never fail in production',
        'Use more classes because they look professional',
        'State safeguards and actual evidence, including the untested concurrency boundary.',
        ['communication', 'reasoning'],
      ],
    ],
  ),
  scenario(
    'py-r-automation',
    'Refactor the customer import job',
    'Sana',
    'Engineering manager',
    'A customer import is difficult to maintain and produces inconsistent totals. Separate its responsibilities and preserve the agreed behavior.',
    `UTF-8 CSV columns customer_id,amount_paise,active. amount_paise is a non-negative integer; active is exactly yes/no. First accepted customer ID wins; preserve arrival order. Sample C1/200/yes, C2/0/yes, C1/999/yes, C3/50/no → active customers C1,C2; total 200. Reject invalid rows with line numbers. API and CLI must share validation. SQL must use bound values.`,
    [
      [
        'What acceptance example should you confirm?',
        'The team says imports should be cleaner.',
        'Confirm active flag interpretation, duplicate behavior, zero amounts, and the sample total',
        'Discard zero-amount customers without asking',
        'Decide that all repeated rows should overwrite earlier rows',
        'Clarify policies that directly affect persisted customer records.',
        ['clarification', 'communication'],
      ],
      [
        'How should CSV parsing and amount conversion be handled?',
        'Input may contain quoted notes and amount text.',
        'Use csv.DictReader and explicit validated integer conversion with row-specific failures',
        'Split on commas and trust every value',
        'Use eval for amounts',
        'Structured parsing plus validation separates format and domain rules.',
        ['files', 'exceptions'],
      ],
      [
        'The total is 1199 instead of 200. What is the likely first investigation?',
        'The repeated C1 row carries amount 999.',
        'Trace whether duplicates are filtered before aggregation',
        'Replace all integers with strings',
        'Increase the timeout',
        'The inflated total suggests repeated customer data reached aggregation.',
        ['debugging', 'fundamentals'],
      ],
      [
        'How should ordered uniqueness be represented?',
        'Customer lookups happen frequently.',
        'Use an accepted-ID set, ordered list, and dictionary for customer lookup',
        'Use a set of amounts',
        'Repeatedly search a concatenated string',
        'Distinct structures preserve identity, ordering, and lookup efficiency.',
        ['structures', 'reasoning'],
      ],
      [
        'Which refactor supports CLI and API consistently?',
        'Both entry points import customers.',
        'Extract shared pure validation/calculation functions into an import-safe module and inject persistence',
        'Duplicate each rule in a new endpoint',
        'Put SQL inside every validation check',
        'Shared reusable rules and composition avoid divergent adapter behavior.',
        ['functions', 'modules', 'oop', 'quality'],
      ],
      [
        'Which save and projection policy is correct?',
        'Valid active customers need persistence and a summary.',
        'Bind SQL values; build pure active projections without mutating original rows',
        'Concatenate SQL and delete inactive rows while traversing',
        'Persist first and validate later',
        'Safe persistence and pure transformations protect data and retained evidence.',
        ['sql', 'comprehensions', 'validation'],
      ],
      [
        'Which regression suite is strongest?',
        'The sample must retain C2 despite zero amount.',
        'Sample output/total, quoted CSV, zero amount, malformed integer, duplicates, and matching API/CLI rules',
        'Only import the module once',
        'Only compare function counts',
        'Behavioral tests verify preservation and consistency across entry points.',
        ['testing', 'quality'],
      ],
      [
        'What should the handoff say?',
        'The acceptance fixtures pass; production import timing is unmeasured.',
        'Shared validation now serves CLI and API; sample outputs match; performance must be measured before a large rollout',
        'Shorter code guarantees faster imports',
        'All future source files will be valid',
        'Explain what changed, the evidence, and the remaining operational check.',
        ['communication', 'reasoning'],
      ],
    ],
  ),
];
